### ISSUE TITLE
Include "rake -P" in "rake -T" output

### ISSUE THREAD

**Issue by mahemoff** [jimweirich/rake#100]
I think "rake -T" output should make note that extra tasks may be listed using "rake -P".

Or at least the --help options listing for -T should mention this.

(I'm not actually sure what the distinction is, so maybe something else makes more sense. But I do think something needs to be done, as it's confusing to create custom rake tasks in Rails, and then find they're not listed by rake -T, which is the main way people expect to find rake tasks. Please feel free to ignore if this is a Rails-specific issue.)

**Comment by zenspider** [comment]
The distinction is whether or not a `desc` has been written for a task. Do this:

```
desc "Does things"
task :blah do
  "things"
end
```

I don't think that `rake -T` should include `rake -P`. Some tasks are undocumented for a reason and `-P` output is very very hairy.

**Comment by jimweirich** [comment]
Rake HEAD currently contains a --all option that will cause -T to show all tasks, even those without a comment.  This will be in the next version of rake.
