### ISSUE TITLE
test_classic_namespace fails on 1.8

### ISSUE THREAD

**Issue by zenspider** [jimweirich/rake#102]
`ruby -I.:lib:test -rubygems test/test_rake_application_options.rb`

produces

```
test_classic_namespace(TestRakeApplicationOptions) [test/test_rake_application_options.rb:274]:
Expected /deprecated/ to match "".
```

**Comment by zenspider** [comment]
PING

**Comment by jimweirich** [comment]
Not currently seeing this problem:

<pre>
$ ruby -v -I.:lib:test -rubygems test/test_rake_application_options.rb
ruby 1.8.7 (2011-06-30 patchlevel 352) [i686-darwin11.2.0]
Run options: --seed 23336
# Running tests:
................................
Finished tests in 0.500489s, 63.9375 tests/s, 331.6756 assertions/s.
32 tests, 166 assertions, 0 failures, 0 errors, 0 skips
</pre>

**Comment by zenspider** [comment]
Hrm... I still am...

```
10012 % ruby -v -I.:lib:test -rubygems test/test_rake_application_options.rb
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]
Run options: --seed 6363

# Running tests:

.........F......................

Finished tests in 0.451505s, 70.8741 tests/s, 367.6593 assertions/s.

  1) Failure:
test_classic_namespace(TestRakeApplicationOptions) [test/test_rake_application_options.rb:298]:
Expected /deprecated/ to match "".

32 tests, 166 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by damphyr** [comment]
There's seems to be a lot of 1.8.7 versions floating around.

```
ruby 1.8.7 (2012-06-29 patchlevel 370) [i686-darwin12.2.0]
Run options: --seed 52915

# Running tests:

................................

Finished tests in 0.594386s, 53.8371 tests/s, 279.2798 assertions/s.

32 tests, 166 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by jimweirich** [comment]
Yes, I upgraded to patchlevel 370 and everything is still passing for me.

Sigh. I hate mystery failures.

The test is checking for the deprecated message printed by "warn".  Ryan, do you have warning suppressed somehow in your Ruby 1.8.7 setup? (e.g. -W0 somewhere)
