### ISSUE TITLE
If require in Rails taks runs Twice from cli

### ISSUE THREAD

**Issue by brutuscat** [jimweirich/rake#106]
Hi I somehow managed to "integrate" rake tasks execution inside rails, so I `require 'rake'` in one initializer for this to work.

Besides some issues with class names polution (Rake::Task for example), the main issue I'm having is that when running a task via cli, with regular rake bin, tasks run twice..

**Comment by brutuscat** [comment]
while this is still an issue I think, I've resolved it like this in my initializer:

``` ruby
if File.basename($0) != "rake"
  require 'rake'
  Rake.load_rakefile 'Rakefile'
end
```

**Comment by jimweirich** [comment]
I'm not sure what you mean when you say "integrate" rake tasks with rails. There's not nearly enough information here for me to reproduce the problem.

If you are still having issues, resubmit with a detailed description of exactly what was done and exactly what errors were occurring.
