### ISSUE TITLE
A typo in rake doc

### ISSUE THREAD

**Issue by pencilcheck** [jimweirich/rake#107]
http://rake.rubyforge.org/files/doc/rakefile_rdoc.html

There is a typo in namespaces where the first namespace should followed by a do but it is not, however the second does.

**Comment by ghost** [comment]
This was fixed in this commit: https://github.com/jimweirich/rake/commit/108e41f9bf504169259dcb86bd57d44771e6c6cf

The issue can be closed @pencilcheck @jimweirich

**Comment by mhenry07** [comment]
Will rake.rubyforge.org be updated with this fix? Thanks
