### ISSUE TITLE
Rake tasks always run tests before running after upgrade to Bundler 1.1

### ISSUE THREAD

**Issue by alanhogan** [jimweirich/rake#114]
Whenever we run _any_ rake command in our Rails 3.2.3 app, tests run. (And when they fail, which currently they are, the rake task does not complete; while that may be best practice, we can’t currently work that like, and would like to be able to skip the tests to save time in some circumstances, anyway.)

Essentially, we need to be able to run **rake without tests** running every time.

We can reproduce this in a **100% new Rails app** when using **bundler 1.1** (but not 1.0).
1. `rails new repro-always-test`
2. `cd repro-always-test`
3. `bundle exec rake -t`

**Expected:** No tests run, and I get a list of available rake tasks.

**Actual:** Tests run (and fail because the database wasn’t created).

```
>>> bx rake -t
** Invoke default (first_time)
** Invoke test (first_time)
** Execute test
** Invoke test:run (first_time)
** Execute test:run
** Invoke test:units (first_time)
** Invoke test:prepare (first_time)
** Invoke db:test:prepare (first_time)
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:abort_if_pending_migrations
** Execute db:test:prepare
** Invoke db:test:load (first_time)
** Invoke db:test:purge (first_time)
** Invoke environment 
** Execute db:test:purge
** Execute db:test:load
** Invoke db:test:load_schema (first_time)
** Invoke db:test:purge 
** Execute db:test:load_schema
** Invoke db:schema:load (first_time)
** Invoke environment 
** Execute db:schema:load
/Users/<username>/Repos/repro-always-test/db/schema.rb doesn't exist yet. Run `rake db:migrate` to create it then try again. If you do not intend to use a database, you should instead alter /Users/<username>/Repos/repro-always-test/config/application.rb to limit the frameworks that will be loaded
```

**Also note:** This is what I get doing a `bundle list` within this brand-new Rails app:

```
Gems included by the bundle:
  * actionmailer (3.2.3)
  * actionpack (3.2.3)
  * activemodel (3.2.3)
  * activerecord (3.2.3)
  * activeresource (3.2.3)
  * activesupport (3.2.3)
  * arel (3.0.2)
  * builder (3.0.0)
  * bundler (1.1.3)
  * coffee-rails (3.2.2)
  * coffee-script (2.2.0)
  * coffee-script-source (1.3.3)
  * erubis (2.7.0)
  * execjs (1.4.0)
  * hike (1.2.1)
  * i18n (0.6.0)
  * journey (1.0.3)
  * jquery-rails (2.0.2)
  * json (1.7.3)
  * mail (2.4.4)
  * mime-types (1.18)
  * multi_json (1.3.5)
  * polyglot (0.3.3)
  * rack (1.4.1)
  * rack-cache (1.2)
  * rack-ssl (1.3.2)
  * rack-test (0.6.1)
  * rails (3.2.3)
  * railties (3.2.3)
  * rake (0.9.2.2)
  * rdoc (3.12)
  * sass (3.1.18)
  * sass-rails (3.2.5)
  * sprockets (2.1.3)
  * sqlite3 (1.3.6)
  * thor (0.14.6)
  * tilt (1.3.3)
  * treetop (1.4.10)
  * tzinfo (0.3.33)
  * uglifier (1.2.4)
```

**Comment by drbrain** [comment]
Use `rake -T` (not `rake -t`) to list available tasks.

Depending upon the configuration of the Rakefile, you may need to perform certain setup tasks before `rake -T` will work.  Consult the author of the Rakefile or rake tasks if this is the case, there is nothing rake can do to prevent Rakefile authors from doing this.

**Comment by alanhogan** [comment]
Oops. Yes, `rake -T` works just fine and runs without tests.

Thanks.
