### ISSUE TITLE
arguments not considered in dependency resolution

### ISSUE THREAD

**Issue by dwt** [jimweirich/rake#119]
I've got the problem that my rake file needs to create files where the content of those files depends on arguments given to that task (debug or release version for example).

Now I'd still like to specify the file creation as a 'file' rule so it only runs if necessary, however there doesn't seem to be a way to tell that file rule that it needs to consider it's arguments to decide if it needs to rerun or not.

Maybe this is the wrong approach as it would mean that rake has to track the arguments used for a file's creation, but I also haven't found a good other way (except for rm'ing the file or creating it with a ruby method).

**Comment by damphyr** [comment]
I tend to use code that creates file tasks using the parameters

``` ruby
def create_file_task(param)
  file "file#{param}"
end

task default=> create_file_task(param)
```

Never forget you can use the full power of Ruby in a Rakefile :)

**Comment by dwt** [comment]
Hm, I may be wrong, but this doesn't print out 'bar' as your answer does suggest:

```
task :foo, :arg1 do |t,args|
    args.with_default(:arg1 => 'baz')
    create_bar = lambda do
        task "bar_#{args[:arg1]}" do
            puts 'bar'
        end
    end

    task :foo => create_bar.call()

    puts 'foo'
end
```

Calling that with `% rake foo` still only prints foo.

**Comment by damphyr** [comment]
You're creating the bar task in the body of the foo task and you're not invoking it.

Unfortunately rake will not reevaluate the dependencies once it's gone through them (I've got a [pull request](https://github.com/jimweirich/rake/pull/103) about that) and in this example you're actually expanding the dependency list _after_ rake is done processing foo's dependencies and entered foo.

**Comment by dwt** [comment]
Well, lets hope your pull request gets pulled then.

**Comment by damphyr** [comment]
That won't help you in the example you posted, because in your case the prereqs have already been processed and your adding more is essentially a noop.

To work around rake for your use case you need an intermediate task:

``` ruby
task :foo,:arg1 do |t,args|
  args.with_default(:arg1 => 'baz')
  task :intermediate=>create_all_prereqs_with_args(args)
  Rake::Task[:intermediate].invoke
end
```

of course if you only have one task you just invoke that in foo and be done with it.

**Comment by dwt** [comment]
Thanks, I'll see how this helps me.
