### ISSUE TITLE
Error at end of tests

### ISSUE THREAD

**Issue by peterklipfel** [jimweirich/rake#120]
This issue seems to only happen at the end of a test suite.  If I run 'rake test' it only happens after all the tests have been run.  The error is raised at the end of rake test:units, rake test:functionals, and rake test:integration.  This error does not occur if the files are run individually; that is, ruby -Itest test/unit/some_test.rb.  

After seeing the monitor.rb in the stack trace, I was wondering if maybe this is a hardware issue.  I just got a new computer, but the I'm running my environment in a virtual machine.  On the other hand, I upgraded from sandy bridge to ivy bridge (perhaps the virtualization is different).

I think this is a rake issue because the entire stack is isolated to my rake gem (except for monitor.rb)

Here's the error after running rake test:units --trace

rake aborted!
Command failed with status (1): [/home/dev/.rvm/rubies/ruby-1.8.7-p358/bin/...]
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/file_utils.rb:53:in `create_shell_runner'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/file_utils.rb:45:in`call'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/file_utils.rb:45:in `sh'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/file_utils_ext.rb:39:in`sh'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/file_utils.rb:82:in `ruby'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/file_utils_ext.rb:39:in`ruby'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/testtask.rb:99:in `define'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/file_utils_ext.rb:60:in`verbose'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/testtask.rb:98:in `define'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `execute'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`invoke_with_call_chain'
/home/dev/.rvm/rubies/ruby-1.8.7-p358/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/application.rb:116:in`invoke_task'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `top_level'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `top_level'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`run'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
/home/dev/.rvm/gems/ruby-1.8.7-p358@global/gems/rake-0.9.2.2/bin/rake:33
/home/dev/.rvm/gems/ruby-1.8.7-p358/bin/rake:19:in `load'
/home/dev/.rvm/gems/ruby-1.8.7-p358/bin/rake:19
/home/dev/.rvm/gems/ruby-1.8.7-p358/bin/ruby_noexec_wrapper:14

**Comment by jimweirich** [comment]
I'm going through the backlog and cleaning out issues. Sorry to take so long to respond. 

Did you ever sort this out?  There's not enough info here for me to reproduce so I'm not sure how to proceed.

**Comment by jimweirich** [comment]
closing for lack of information
