### ISSUE TITLE
Delayed expansion of task names and prerequisites & passing parameters to prerequisites

### ISSUE THREAD

**Issue by norswap** [jimweirich/rake#124]
## Motivation in 3 problems

The following scenario often happens to me. I have a main task performing some logic, and I need a second task which performs nearly the same thing as the first, with one or two changes.

In those cases, I tend to use this construct:

```
task :first do .. $SOMEVAR.. end

task :second => [:set, :first] 

task :set do $SOMEVAR = X end
```

Already you might notice that is a bit verbose, and not very elegant. Let's call this `problem 1`. But things get worse if you need to change the prerequisites dynamically.

```
task :set do Rake::Task[:first].prerequisites << "new_prerequisite"
```

Let's call this `problem 2`

Finally, a last problem I'd like to underline is that there is no way to match a prerequisite to a task other than using regexp. For instance, we can't have a predicate function that could match prerequisites names. Honestly, I've never encountered this problem, but it fits well with the proposed solution to `problem 2`. Let's call this `problem 3`.
## A solution to `problem 1`, to be implemented in the core

The solution is very obviously to allow passing parameters to prerequisites. Since tasks can already receive parameters from the command line, why not when called as prerequisites ?

Syntax is an issue tough. I suppose somthing like `[:prereq, "first_param", "second_param"]` or maybe the slighty clearer if more verbose `{:prereq => ["first_param", "second_param"]}`
## A hackish solution to `problem 2`

Actually, there is one instance in rake where delayed expansion is possible, and that is for rules. So my idea was to solve the prerequisites problems by doing something like:

```
rule "//first" => proc {
  .. $PREREQ_VAR ..
} do ... end
```
## A clean solution to `problem 2` and `problem 3`, to be implemented in the core

The solution is simply to allow a proc as name parameter and prerequisite parameter. A name proc would be called with a prerequisite name as parameter and would return a boolean indicating a match. A prerequisite proc would be called when the task is invoked.
## Outro

Please, let me know of any oversight I might have been guilty of. If there are hackish (or even totally clean) ways to achieve what I expose, I would very much like to hear of them. Don't hesitate to ask for clarifications.

If this proposition garners support, I am ready to spend some times to implement those features.

**Comment by jimweirich** [comment]
Seems to me that problem 1 is better solved with methods than rake tasks.  Solution 2 seems to usurp existing rule syntax and would hence be incompatible. And I'm not sure I'm understanding where you are going with the solution for 2/3.
