### ISSUE TITLE
rake test tries to load a file named allo (Windows only)

### ISSUE THREAD

**Issue by maoueh** [jimweirich/rake#129]
I'm having a hard time understanding what's going on here and wondering if this is a badly configured system or a bug hurting all Windows boxes. Let me explain.

Recently, I wanted to create some unit tests for a gem file I'm creating. Some, followed some tutorials and created a rake task to run the tests. However, for an unknown reason, rake always complains not being able to load a file named `allo` from my gem folders. Here the small trace the is output running `rake test` in the root folder:

```
$ rake test
<internal:lib/rubygems/custom_require>:29:in `require': no such file to load -- c:/Users/Matt/Work/gems/simple/allo (L
oadError)
        from <internal:lib/rubygems/custom_require>:29:in `require'
        from c:/Ruby/1.92/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'
        from c:/Ruby/1.92/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:4:in `select'
        from c:/Ruby/1.92/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [c:/Ruby/1.92/bin/ruby.exe -I"lib;test" -I"...]

Tasks: TOP => test
(See full trace by running task with --trace)
```

I just can't understand why it tries to load a file named `allo` from my gem root folder. So, tried this same gem on my Mac and it works as expected without any problems.

It seems to be a problem on my Windows box only. What I'm not sure is if this is a badly configured Windows box or a bug affecting any Windows boxes.

On Windows, I'm running ruby `and rake`. On my Mac, its ruby `1.8.7` and I'm unsure about the rake version, I would need to check.

I have a very slimdown gem structure that reproduces the problem for me. I'm in the process of gisting it right now. Will add it to this issue in a comment when it's finished.

Regards,
Matt

**Comment by maoueh** [comment]
Here the [gist](https://gist.github.com/3885660) that I used to reproduce the problem on by machine. Tell me if you need further information to hunt this down.

**Comment by maoueh** [comment]
I updated rake on my Mac to its latest version (0.9.2.2) and it works as expected.

**Comment by jimweirich** [comment]
Line 15 of the rake_test_loader.rb file attempts to load a file given to it from the command line.  It does do a File.expand_path on the argument, so somehow File.expand_path(SOMETHING) is expanding to "c:/Users/Matt/Work/gems/simple/allo".

That SOMETHING is probably one of the files passed to the test task.  Check your rake file to see how you are configuring the test task and if any Junk is getting in there.

**Comment by maoueh** [comment]
@jimweirich I will try to debug this further down later today. But I doubt its a misconfiguration somewhere because I tried another ruby project found on the internet and the same errors popped. 

When I have more information, I will come back to post it.

**Comment by maoueh** [comment]
Ok sorry for the false report :$

In fact, everything is configured correctly, the problem is that I once set a TEST environment variable within a `.profile`. So, when was doing `rake test` it was instead doing `rake test TEST=allo`. I was not aware of the possibility to invoke `rake test TEST`. Guess I learnt something :)

Regads,
Matt
