### ISSUE TITLE
Two bad href links in installed rdocs.

### ISSUE THREAD

**Issue by DouglasAllen** [jimweirich/rake#132]
Nobody uses gem server right? Well I did just today and from index.html lines 114 and 132 I had

114 href="http://rake.rubyforge.org/files/doc/command_line_usage.rdoc"

132
href="http://github.com/jimweirich/rake."

So far.

I fixed mine but just thought that you should be made aware of this.
Thanks!

**Comment by jimweirich** [comment]
Thanks.  This is fixed in HEAD.
