### ISSUE TITLE
Deprecated DeprecatedObjectDSL methods break RSpec expectations

### ISSUE THREAD

**Issue by zephyr-dev** [jimweirich/rake#136]
Running this code: https://gist.github.com/3946526

Produces

``` ruby
NoMethodError: private method `import' called for Foo:Class
        from (irb):8
        from /Users/pivotal/.rvm/rubies/ruby-1.9.3-p194/bin/irb:16:in `<main>'
```

Not sure if this is definitely a problem with Rake making these methods private or just RSpec's inability to mock a private method.

**Comment by jimweirich** [comment]
Well both.

The DeprecatedObjectDSL will go away in the next major releases of rake.

**Comment by zephyr-dev** [comment]
Thanks!
