### ISSUE TITLE
rake-10.0.0.beta.1

### ISSUE THREAD

**Issue by willglynn** [jimweirich/rake#137]
[rubygems.org](https://rubygems.org/gems/rake) lists a `10.0.0.beta.1` released the same day as `0.9.3.beta.3`, but I can't find any reference to that version in git. (I also think it's strange to skip 9 major versions all at once anyway.) Is this an intentional release?

**Comment by drbrain** [comment]
Yes.

**Comment by willglynn** [comment]
Ah, you have since added the [10.0.0 release notes](https://github.com/jimweirich/rake/blob/next-major-release/doc/release_notes/rake-10.0.0.rdoc), explaining the versioning to me along with anyone else who is confused.

**Comment by jimweirich** [comment]
0.9.3 and 10.0 will be released more or less simultaneously with the same feature set, but with all the deprecated features removed from version 10.  

Also, the Rake 10 code base is the the branch next-major-release.
