### ISSUE TITLE
RDoc failure in lib/rake/phony.rb

### ISSUE THREAD

**Issue by caryp** [jimweirich/rake#143]
I received an error when trying to install ri doc for rake 10.0.0.   Any ideas why this would be occurring?

Distributor ID: Ubuntu
Description:    Ubuntu 10.04.4 LTS
Release:        10.04
Codename:       lucid

root@kbubu12h1grub:~# gem -v
1.3.7
root@kbubu12h1grub:~# ruby -v
ruby 1.8.7 (2010-01-10 patchlevel 249) [x86_64-linux]
# gem install rake

Successfully installed rake-10.0.0
1 gem installed
Installing ri documentation for rake-10.0.0...

RDoc failure in lib/rake/phony.rb at or around line 11 column 9

Before reporting this, could you check that the file
you're documenting compiles cleanly--RDoc is not a
full Ruby parser, and gets confused easily if fed
invalid programs.

The internal error was:

ERROR:  While executing gem ... (NoMethodError)
    undefined method `name' for #RubyToken::TkLPAREN:0x7f708cbf09b0

**Comment by drbrain** [comment]
Which version of rdoc?

**Comment by jimweirich** [comment]
The phony task has a some slightly unusual (but quite legal) syntax going on.  Try a recent version of the rdoc gem. I'm using rdoc-3.12 to build locally with no problem.

**Comment by jimweirich** [comment]
Simplified the phony task syntax a bit and marked it with :nodoc:. I think that should fix things.
