### ISSUE TITLE
Rake 10 TestTask exits successfully even when tests fail

### ISSUE THREAD

**Issue by samg** [jimweirich/rake#144]
I've created a reproduction case here:
https://github.com/samg/reproduce-bug-in-rake-testtask

Rake TestTasks will exit 0 even when tests fail.

I believe I've traced the bug to this commit:
89aed93b4a7b475a4400ddf2032209855a7bc766

The default task behavior (when a block isn't passed to `ruby` or `sh` methods) is to `fail` unless `ok` is set to true.
- https://github.com/jimweirich/rake/blob/master/lib/rake/file_utils.rb#L53

Here signal exceptions are handled but a failing test suite (that wasn't signaled) will cause rake to return a successful status code, even though the suite failed.  I've noticed this behavior in our test environment.

**Comment by jimweirich** [comment]
Thanks. Investigating.

**Comment by jimweirich** [comment]
Added a test for the exit status of the testtask.  Fixed in master.  Will release bug fix version soon.

**Comment by samg** [comment]
Awesome! Thanks!
