### ISSUE TITLE
Unrecognized --trace option 'db:migrate' 

### ISSUE THREAD

**Issue by alexch** [jimweirich/rake#145]
Using rake 10.0.1 inside a rails 3.2.8 app, the command 

```
rake --trace db:migrate
```

gives the error

```
Unrecognized --trace option 'db:migrate' 
```

Looks like "--trace" now thinks it accepts an option, when it's really just a flag. 

`rake db:migrate --trace` works as usual.

**Comment by jimweirich** [comment]
Actually, trace now does take a option.  You say '--trace=stdout' or '--trace=stderr' to tell it where to place the output.  However, the intention was that if you didn't say anything, it would default to stderr.

I'll have to see if this is something that can be corrected in the option parser.

**Comment by benhutchison** [comment]
+1.

The docs at https://github.com/jimweirich/rake/blob/master/doc/command_line_usage.rdoc don't seem to mention that an option is now required. 

Many of our exiting scripts were using --trace without an option, and broke when we upgraded the rake gem. So if a default option could be added that would be appreciated.

**Comment by jimweirich** [comment]
Yep, its an issue with the option parser.  I've changed it so that both --trace and --backtrace require an equal sign in order to specify an option.

The fix is in head and will probably to out early next week in the next minor point release.
