### ISSUE TITLE
invalid option: --reduce-compat

### ISSUE THREAD

**Issue by lawrencepit** [jimweirich/rake#151]
```
$ rake --version
rake, version 10.0.2
$ rake --reduce-compat sometarget
invalid option: --reduce-compat
```

**Comment by jimweirich** [comment]
The --reduce-compat option is no longer available because Rake 10 had removed all deprecated features and is unable to reduce compatibility any further.

In other words, you automatically get the effect of reduce-compat without needing the command line flag.

**Comment by lawrencepit** [comment]
I see, joy! 

Small thing, I guess the following can then be removed from /bin/rake (in origin/next-major-release) :

```
module Rake
  REDUCE_COMPAT = true if ARGV.include?("--reduce-compat")
end
```

and `require 'rake/ext/module'` from lib/rake.rb

**Comment by jimweirich** [comment]
Thanks for the catch.
