### ISSUE TITLE
CHANGES file is out of date

### ISSUE THREAD

**Issue by parndt** [jimweirich/rake#156]
Latest version shown is 0.9.3 :-)

**Comment by zzak** [comment]
You could refer to [release notes](https://github.com/jimweirich/rake/tree/master/doc/release_notes), maybe merge them into `CHANGES`

**Comment by parndt** [comment]
Thanks! Looks like release notes is also out of date as there's no mention of rake 10..

**Comment by zzak** [comment]
I found them: https://github.com/jimweirich/rake/tree/rake-10.0.3/doc/release_notes

There is a branch for rake 10: https://github.com/jimweirich/rake/tree/next-major-release

**Comment by drbrain** [comment]
You need to be on the rake 10 branch, not master: https://github.com/jimweirich/rake/tree/next-major-release/doc/release_notes

**Comment by parndt** [comment]
Should the CHANGES file be removed in favour of the release notes?

**Comment by jimweirich** [comment]
Yes, I think the CHANGES file is a holdover from an older workflow.

**Comment by zzak** [comment]
Thanks Jim!

I'm just going to add this commit for future reference: 85fcaa6
