### ISSUE TITLE
Conflict between Ruby 1.9.2 and rake 10.0.3 for rake/rdoctask vs. rdoc/task

### ISSUE THREAD

**Issue by tadman** [jimweirich/rake#157]
Ruby 1.9.2p290 comes bundled with a `rdoc/task.rb` file that contains the following:

```
require 'rdoc'
require 'rake'
require 'rake/rdoctask'
```

`rake` 10.0.3 contains a `rake/rdoctask` that contains the following:

```
fail "ERROR: 'rake/rdoctask' is obsolete and no longer supported. Use 'rdoc/task' (available in RDoc 2.4.2+) instead."
```

I'm not sure how you're supposed to follow this advice since when you do, it fails.

I understand this is a deprecated interface, but if the installed Ruby version doesn't have the replacement, it doesn't seem to be possible to do that. As a note, Ruby 1.9.2p290 comes bundled with its own `rake/rdoctask` that should work, but as `rake` puts itself first in the load path, it can't be loaded.

Removing the version bundled with `rake` might be a better idea than stomping the one bundled with Ruby.

**Comment by tadman** [comment]
A horrible hack to get this working is to demote the `rake` includes to have a lower priority in your `Rakefile`:

```
# ...

# Add this line just before the require to fix the deprecation notice
$LOAD_PATH.sort_by! { |p| p.match(%r[/rake\-]) ? 1 : 0 }

require 'rdoc/task'
```

This will use the legacy `rdoc/task` associated with whatever Ruby you have installed instead if you need to work around this issue.

**Comment by sanemat** [comment]
I only use `require 'rdoc/task` https://github.com/bblimke/webmock/blob/master/Rakefile#L49 but I met this:

```
rake aborted!
ERROR: 'rake/rdoctask' is obsolete and no longer supported. Use 'rdoc/task' (available in RDoc 2.4.2+) instead.
/Users/sane/work/ruby-study/webmock/Rakefile:49:in `<top (required)>'
```

This is only 1.9.2, and no error with 1.8.7 and 1.9.3, 2.0.0. https://travis-ci.org/bblimke/webmock/jobs/4122811

**Comment by ronen** [comment]
+1 likewise getting travis-ci failure with ruby 1.9.2 but not 1.9.3  https://travis-ci.org/lomba/schema_plus/builds/4201177

**Comment by jimweirich** [comment]
You need to make sure that Rake is using a verison of RDoc that is 2.4.2 or later (as mentioned in the error message).

You can do this by either using a Gemfile and executing Rake with bundle exec.  This Gemfile worked for me:

``` ruby
gem 'rdoc', ">= 2.4.2"
gem 'rake'
```

Or you can use a gem command in your rakefile to make sure you get the right version of rdoc.  This Rakefile also worked for me:

``` ruby
gem 'rdoc', ">= 2.4.2"
require 'rdoc/task'
```
