### ISSUE TITLE
Feature request: alias tasks

### ISSUE THREAD

**Issue by gredler** [jimweirich/rake#16]
It would be nice to be able to alias task names to shorthand names, so that e.g. `rake package_client` could be shortened to `rake pc` (if that's a task that you've defined in your rakefile).
### Before:

```
desc "Packages all of the client files."
task :package_client => :foo do
    ...
end
```

rake -T
rake clean           # Removes all build artifacts.
rake package_client  # Packages all of the client files.
### After (just an example of what it might look like):

```
desc "Packages all of the client files."
task [:package_client, :pc] => :foo do
    ...
end
```

rake -T
rake clean           # Removes all build artifacts.
rake package_client / pc  # Packages all of the client files.

**Comment by jimweirich** [comment]
I generally do a:

```
task :pc => package_client
```

for any aliases I need.  Seems to me that this is adequate.

**Comment by gredler** [comment]
Yeah, I do the same; the aliases just don't show up when you run "rake -T".

**Comment by jimweirich** [comment]
You can try this method:

```
def alias_task(alias_name, task_name)
  t = task alias_name => task_name
  t.comment = Rake::Task[task_name].comment
end
```

Just make sure to call it after the original task is defined.

**Comment by rubiii** [comment]
if it's that easy, i vote for this to be included in rake itself.

**Comment by simrb** [comment]
Here, i got a problem, when our task with the parameter that cannot be passed to the origin task
For example, 
put ' task :s => "db:schema"  ' this in Rakefile , and assuming we have a task called db:schema with a parameter

now, we type the commend 'rake s[name]' in terminal, it can be not passed the parameter to task db:schema,
but the command 'rake db:schema[name]' is ok.

**Comment by amirrajan** [comment]
Just came across this GH issue (which helped me solve my problem). RIP @jimweirich, thank you for all that you've done.
