### ISSUE TITLE
rake aborted! "\xC2" on US-ASCII

### ISSUE THREAD

**Issue by Mallikarjunay** [jimweirich/rake#162]
rake aborted!
"\xC2" on US-ASCII

I am getting this error for my project

Trace : 
ruby -e 'puts Encoding.default_external.to_s + "," + Encoding.default_internal.to_s'

if i run this, i am getting UTF-8,

I am using UBUNTU 11.04

but , still i am getting this error ?

How to fix this ?

**Comment by jimweirich** [comment]
There's not near enough information provided here for me to be helpful.  It sounds like a you are trying to read (or load) a file that has US-ASCII encoding turned on, yet has a non-ASCII character in it.  A stack trace might help you track down the issue.

**Comment by Mallikarjunay** [comment]
This problem has been fixed by assigning  LC_CTYPE="en_US.UTF-8"
