### ISSUE TITLE
Task tab completion

### ISSUE THREAD

**Issue by joallard** [jimweirich/rake#171]
This is a feature request. I don't know whether that has been already discussed, but I figured I'd ask.

Is there some interest to introduce tab completion in the shell for task names. A bit like Git does with basically everything, namely branch names. 

That would be quite useful as I can't always recall what the task names are for all the projects.

**Comment by shreyasbharath** [comment]
This would be a great feature if it is possible to implement.

We generate a number of tasks dynamically so it'd be really useful.

**Comment by jimweirich** [comment]
This is outside the scope of rake itself. 

However, if someone wanted to contribute something, we would make them available somehow. I'm not sure distributing the shell extensions in the rake gem makes sense, but we could certainly put them on a website and point some links at them.

**Comment by joallard** [comment]
Good point. I could see how this would be out of scope, and I understand the scope creep concerns, but really I don't see how this would be so far from Rake's core function. Basically, we're listing the available tasks, and giving that into a format to the shell to be completed easily. Rake is also pretty much used within a shell context, so I could see that making sense.

From a user's perspective, is there any case where a user _wouldn't_ want that behavior or in which we would classify that as an extension? For instance, are there other shells that wouldn't support this? Is there a sizeable part of users who'd think "maybe I don't want this"? At what expense would that come? I'm not sure.

For sure, in the end, making this into Rake itself or as an extension is all right by me, but in a thought experiment sense, I'm thinking, "why not?". I'm being Clippy here asking "Are you sure?" ;o)

**Comment by jimweirich** [comment]
There's two components to tab completion. (1) Rake providing the list of tasks and (2) the Shell integration required for actual completion.

I'm saying (2) is out of scope for rake. Most tab-completion solutions that I'm aware of just use the -T output from rake, so (1) is already covered for the most part.

If you have specific requirements for a better version of (1), I'd be glad to hear it.
