### ISSUE TITLE
Run :default task in namespace when trying to run namespace

### ISSUE THREAD

**Issue by grosser** [jimweirich/rake#176]
Would you accept a pull request that implements this:

``` Ruby
namespace :foo do
  task :default do
    puts "Running default!"
  end
end
```

``` Bash
rake foo
Running default!
```

(If a tasks with the exact name is defined and a default task, picks the tasks with the exact name)

**Comment by jimweirich** [comment]
Probably not.  Doing that would conflict with a top-level task named foo, and I'm not a fan of ambiguity.

You could add one line:

``` ruby
task :foo => "foo:default"
namespace :foo do
  task :default do
    puts "Running default!"
  end
end
```

**Comment by grosser** [comment]
I'm trying to avoid the ugliness of

``` Ruby
task :foo => "foo:default"
```

I would think that the foo task wins, if you think that's to ambiguos then just close this issue :)
