### ISSUE TITLE
rake's executable conflicts with ruby 2.0.0-p0 rake

### ISSUE THREAD

**Issue by mjaros** [jimweirich/rake#178]
When updating rake on a new Ubuntu 12.04 server with a fresh install of Ruby 2.0.0-p0 I am getting this:

```
Updating rake
Fetching: rake-10.0.3.gem (100%)
rake's executable "rake" conflicts with /home/git/.rbenv/versions/2.0.0-p0/bin/rake
Overwrite the executable? [yN]
```

Is it safe to override the executable?

**Comment by drbrain** [comment]
Yes, please see http://bugs.ruby-lang.org/issues/5060
