### ISSUE TITLE
Awkward API for PackageTask/TestTask/MultiTask & GemPackageTask

### ISSUE THREAD

**Issue by leehambley** [jimweirich/rake#184]
This is as shot in the dark (_[don't push your pull requests](http://www.igvita.com/2011/12/19/dont-push-your-pull-requests/)_). But I wanted to ask if there was any outstanding reason for not making the API for these a little simpler (that is to ask, why doesn't it work like this)

``` ruby
package 'mypackage', :noversion, files: FileList.include("lib/**/*.rb")
```

(and similar APIs for test task, etc)

If it would be accepted, I'd certainly have a shot at writing it, I'm actually looking personally for something simpler, overall:

``` ruby
tarball :mystuff, FileList.include("lib/**/*.rb")
```

Naturally I could adapt the `Rake::DSL` for this special case, but perhaps a wider change would be welcomed?

**Comment by leehambley** [comment]
This small patch might do what I need, I'm about to disappear out of the office, so I can't really test it, but thoughts and feedback would be welcomed:

``` ruby
require 'rake/packagetask'
module Rake
  module DSL
    def tarball(name, file_list)
      Rake::PackageTask.new(name, :noversion) do |p|
        p.need_tar      = false
        p.need_tar_gz   = true
        p.need_tar_bz2  = false
        p.need_zip      = false
        p.package_files = file_list
      end
    end
  end
end
```

**Comment by jimweirich** [comment]
I am disinclined to introduce a tarball DSL command that so incomplete w.r.t the package task library. I would not object to someone cleaning up the package interface, but this looks rather incomplete and addresses only a very small subset of the general need.

Edit: changed "would" to "would not"

**Comment by leehambley** [comment]
Acknowledged @jimweirich thanks for the comment, I also noticed that it's a little awkward with the existing API, it's certainly intended for packaging _one_ thing from the repository, and not for tarballing up multiple directories in the PWD for packaging.

Closing the issue as "didn't give it enough thought before opening mouth". Thanks! :rocket:
