### ISSUE TITLE
Lazy variable initialization

### ISSUE THREAD

**Issue by bradgessler** [jimweirich/rake#186]
I've found myself needing to declare variables in Rake as such:

``` ruby
# This will break if I run `rake -T`
namespace :db do
  db = URI.parse(ENV['DATABASE_URL'])
  task :dump do
    "foo #{db.host} bar"
  end
end
```

The problem with this is that when I run rake -T without the variable, I might get an error if the ENV var isn't defined.

I propose `let` rspec semantics where variables can be defined inside of a `let` block and lazily read as needed by rake tasks:

``` ruby
# rake -T wouldn't evaluate the code inside the `let` block, so its all good!
namespace :db do
  let(:db) { URI.parse(ENV['DATABASE_URL']) }
  task :dump do
    "foo #{db.host} bar"
  end
end
```

`let` blocks could be scoped by namespace, so if a global `let` is defined, something that's closer to the namespace would be given preference over the global `let`.

**Comment by damphyr** [comment]
And why won't you declare the variable inside the task?
Even if there's a whole lot of them, creating a configuration class makes it a whole lot simpler.

I often use environment variables sometime with defaults, sometimes without. I tend to create a module that wraps access to them so I can do things like 

``` ruby
def db 
   ENV['DATABASE_URL'] ? URI.parse(ENV['DATABASE_URL']) : "whatever"
end
```

even established a use for the bang where db! will throw a "you really have to provide a value" exception.
Include the module within the task and you have access to this without messing up your namespace.

``` ruby
module Configuration
  def db
      "foo"
  end
end

task :bar
  include Configuration
  puts db
end
```

Added advantage: you can rdoc the module and get a nice description of your configuration parameters.

**Comment by michaeljbishop** [comment]
You could also solve this with a simple lambda (similar to what I imagine Python's `let` is).

```
namespace :db do
  db = lambda{ URI.parse(ENV['DATABASE_URL']) }
  task :dump do
    "foo #{db.call.host} bar"
  end
end
```

I run into this a lot. Rake is essentially a Promise-Based system (a task is a very powerful promise) but you can use a vanilla promise wherever you like. This blog post goes into that in more detail.

http://www.numerical-garden.com/blog/2013/3/29/learning-rake-what-is-rake-the-library.html

**Comment by bradgessler** [comment]
Consider a connection resource:

``` ruby
def db
   Sequel.connect(ENV['DATABASE_URL'])
end
```

and a task to create a DB:

``` ruby
task :migrate do
  db.migrate(ENV['VERSION'])
end
```

To properly use this with `def`'s without opening multiple database connections requires manual memoization:

``` ruby
def db
   @db ||= Sequel.connect(ENV['DATABASE_URL'])
end
```

While this isn't a huge deal it goes against the grain of rake's promise-based syntax. As it stands, promising resources is something that is done manually with a `def` block.

I'd argue the `def` approach that you propose works and feels best in a class-based promise system like Thor:

``` ruby
class Database < Thor
  desc "migrate", "Migrate the database"
  def migrate
    puts "I'm a thor task!"
  end
private
  def db
    @db ||= Sequel.connect(ENV['DATABASE_URL'])
  end
end
```

and that a `let` approach works best in rake.

So that you know this isn't contrived, the particular use-case I'm running into is that I'm connecting to an S3 bucket for storing various backups. I need to call the same S3 bucket from various rake tasks. Seeing all of the variables that are at play in my tasks feels much better:

``` ruby
namespace :db do
  let(:db)            { URI(ENV['DATABASE_URL']) if ENV['DATABASE_URL'] }
  let(:db_bucket)     { s3.buckets.find(ENV['AWS_DATABASE_BACKUP_BUCKET']) }
  let(:passphrase)    { ENV['PASSPHRASE'] }
  let(:backup_path)   { 'backup.gz.encrypted' }
  let(:restore_path)  { 'restored.sql' }
  let(:max_backups)   { 30 }
  let(:remote_backup_key) { "#{timestamp}-#{backup_path}" || ENV['REMOTE_BACKUP_KEY'] }

  # Tasks here...
end
```

The explicitness of the `let` blocks also serves as more readable code for the next dev that might have to crack this open.

**Comment by drbrain** [comment]
As tasks are only executed once, they seem equivalent to `let`:

``` ruby
namespace :db do
  task :connection do
    abort 'please set DATABASE_URL' unless ENV['DATABASE_URL']
    @connection = Sequel.connect ENV['DATABASE_URL']
  end

  task dump: %w[connection] do
    # Use @connection …
  end
end
```

Using `task` also allows you to give the user a nice message telling them what to do if they're missing some required action.

**Comment by jimweirich** [comment]
While I'm a big fan of "let" in RSpecs, I'm not convinced they are a good fit for Rake.

In most of my Rakefiles, I've solved this by building a Ruby object that did the heavy lifting and just invoke the object in the task. This has the benefit of being much easier to unit test.

By making things lazy, you lose control of when they are executed.  By making lots of things lazy, I fear you could easily change semantics just by referencing a lazy variable earlier than expected.  (E.g.  values that depend on Environment variables when  you have some tasks that change the environment variables). 

Perhaps this fear is unfounded, but I would like to get a feel for it before making such a radical change to the Rake program itself.

Could this be done in an optional gem to get some experience with it before incorporating to Rake itself?

**Comment by michaeljbishop** [comment]
I think using an actual Promise would accomplish much of what you want. The code in the block of the promise is guaranteed to only execute once.

Here's the promise code:
  https://github.com/michaeljbishop/promising-future/blob/adds-parameter-capturing/lib/promise.rb

```
require 'promise'

namespace :db do
  db = promise{URI.parse(ENV['DATABASE_URL']))}
  task :dump do
    "foo #{db.host} bar"
  end
end
```

If you want to capture the value of `ENV['DATABASE_URL']` at the time of the promise-instantiation (and insulate yourself from Jim's scenario where the environment is changed), you can pass it in as a variable. When running `rake -T` as you are, it will simply capture the nil value but the block won't ever use it:

```
require 'promise'

namespace :db do
  db = promise(ENV['DATABASE_URL']){|dburl| URI.parse(dburl))}
  task :dump do
    "foo #{db.host} bar"
  end
end
```

Also keep in mind that there is already non-public code for a promise object in Rake. That could be reviewed and made into something more publicly useful.

I understand the concern about mutating the environment, but is that a common scenario? Seems akin to using a modifying a lot of global variables.

**Comment by damphyr** [comment]
Yes modifying the environment is "evil" and akin to using global variables
but in some cases it cannot be avoided.
Certain tools invoked through rake might depend on the environment for
parametrization (I have a problematic candidate like this) and which point
I just modify the ENV variable from within rake to control what parameters
pass. Granted not the scenario we are discussing here where the environment
is rake's input, but early binding of environment variables would be
unfortunate in this case.

On Mon, Apr 15, 2013 at 7:52 PM, Michael Bishop notifications@github.comwrote:

> I think using an actual Promise would accomplish much of what you want.
> The code in the block of the promise is guaranteed to only execute once.
> 
> Here's the promise code:
> 
> https://github.com/michaeljbishop/promising-future/blob/adds-parameter-capturing/lib/promise.rb
> 
> require 'promise'
> 
> namespace :db do
>   db = promise{URI.parse(ENV['DATABASE_URL']))}
>   task :dump do
>     "foo #{db.host} bar"
>   end
> end
> 
> If you want to capture the value of ENV['DATABASE_URL'] at the time of
> the promise-instantiation (and insulate yourself from Jim's scenario where
> the environment is changed), you can pass it in as a variable. When running rake
> -T as you are, it will simply capture the nil value but the block won't
> ever use it:
> 
> require 'promise'
> 
> namespace :db do
>   db = promise(ENV['DATABASE_URL']){|dburl| URI.parse(dburl))}
>   task :dump do
>     "foo #{db.host} bar"
>   end
> end
> 
> Also keep in mind that there is already non-public code for a promise
> object in Rake. That could be reviewed and made into something more
> publicly useful.
> 
> I understand the concern about mutating the environment, but is that a
> common scenario? Seems akin to using a modifying a lot of global variables.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jimweirich/rake/issues/186#issuecomment-16400612
> .

## 

http://www.ampelofilosofies.gr

**Comment by michaeljbishop** [comment]
Regardless of this particular issue, I think have a solution for you!

I don't know the process by which your Rakefile executes subprocesses so I apologize if this is not applicable, but you might try passing a modified copy of `ENV` to your subprocesses as you execute them. In `Kernel#system` (which Rake's `FileUtils#sh` relies on) you can pass overrides to the subprocess environment if the first parameter is a hash.

```
task :print_pwd do
  puts "TACO=#{ENV['TACO']}"
  puts "PWD=#{ENV['PWD']}" # not-overriden
end

task :new_pwd do
  overrides = {'TACO'=>'BELL'}
  sh overrides, "rake", "print_pwd"
  sh overrides, "rake print_pwd" # also works with command-string
end
```

outputs...

```
> rake print_pwd
TACO=
PWD=/Users/michaeljbishop/example

> rake new_pwd
{"TACO"=>"BELL"} rake print_pwd
TACO=BELL
PWD=/Users/michaeljbishop/example
{"TACO"=>"BELL"} rake print_pwd
TACO=BELL
PWD=/Users/michaeljbishop/example
```

All the best,

_ michael

---

http://www.numerical-garden.com

**Comment by bradgessler** [comment]
@michaeljbishop your latest proposal doesn't address the core issue, which is the proposal of `let` as additional syntactical sugar for rake. The second proposal also skirts around the issue of adding syntax. Of course there are numerous work arounds. I've already monkey patched my version Rake runtime so that `let` blocks work. I'd like to refocus this thread on whether or not there's any desire to add `let` blocks into Rake.

My point is that rake itself is syntactic sugar. Thor has proven that a promise task-oriented DSL can use `def` blocks to achieve the same thing a `task` block does, and thus Thor lends itself to lazy initialization without globals very well via `private; def blah; @blah ||= Something.new; end;` as an instance method.

Rake on the other hand is a DSL that lays tasks out differently than Thor. I think of it as a great way to stitch together a bunch of shell commands with Ruby code and run a sequence of commands to knock out a larger task. The only thing that I feel Rake is missing is lazy variable instantiation since it seems to flow with the rest of the "grain" in rake.

The question is: to `let`, or not to `let`?

**Comment by jimweirich** [comment]
Ok, after a lot of thought and some investigation I'm going to close and reject this issue.  There are several reasons.

First of all, there is no good place to put the "let" defined lazy methods.  Since namespaces don't introduce real method scopes, the only real possibility for a scope is the DSL module.  But that module is widely used.  Defining a lazy let inside a nested scope and having it appear in the global DSL namespace is surprising behavior. Allowing nested lets to override outer lets would require a way from global code to determine the current dynamic execution scope (i.e. the list of tasks currently executing).  Although the tasks themselves currently track that internally, for non-task code to determine that, it would have to find the currently executing task (e.g. something like Rake.current_task), and that information is thread-based, not global, so the complications multiply.

Next, there is a semantic issue.  Given:

``` ruby
namespace "a" do
  let(:foo) { 10 }
  let(:bar) { foo + 1 }
  task :print do
    puts "a bar = #{bar}"
  end

  namespace "inner" do
    let(:foo) { 12 }
    task :print do
      puts "a:inner bar = #{bar}"
    end
  end
end

task :default => ["a:print", "a:inner:print"]
```

Running "rake" with the above Rakefile, what should be the output? The following seems logical:

```
a bar = 11
a:inner bar = 13
```

Now, would your answer change if "a:inner:print" task had the "a:print" task as a dependency?

I'm sure this could all be worked out, but to me the correct answer isn't clear to me, I'm very reluctant to innovate in this area.

Perhaps, someday, the Rake namespaces will become full class scoped entities with a place to hang lazy let definitions, but we are not there yet.

If someone would like to experiment in a rake add-on, I would be interested in the results. But I'm not ready to do this in the core rake yet.
