### ISSUE TITLE
Using tasks from global Rakefile 

### ISSUE THREAD

**Issue by mulderp** [jimweirich/rake#188]
I really start to love the global Rakefile a lot.
However, something which I am confused about, and which might be improved is when I am in e.g. a Rails project which has its own Rakefile, it's not clear to me how I still could access rake tasks from `~/.rake`

Any ideas? I would also work on a PR if someone would point me to a good way to solve this.

**Comment by jimweirich** [comment]
``` ruby
rake -g global_rake_task_name
```

**Comment by mulderp** [comment]
Thanks!

Indeed, in a directory of a Rails project:

```
rake -T -g -a    # lists alls global tasks
```

However, in directories without a Gemfile, I can get a:

```
rake -g -T
Could not locate Gemfile
```

While:

```
gem list | grep rake
rake (10.0.4)
```

Is this expected?

I also have:

   which rake
   /Users/pmu/.rbenv/shims/rake

**Comment by jimweirich** [comment]
This sounds like a bundles issue. Rake has no knowledge of Gemfiles.
