### ISSUE TITLE
Some backtraces are never shown

### ISSUE THREAD

**Issue by jjb** [jimweirich/rake#189]
I was having a problem in a rake task (assets:precompile), and the backtrace was always getting swallowed. The output was always like so:

```
** Execute assets:precompile:primary
uninitialized constant #<Class:0x007fae6cb3dd88>::FooBar
Command failed with status (1): [/Users/john/.rbenv/versions/1.9.3-p385-per...]
```

No matter how I invoked rake (`--verbose --trace --backtrace` all on), the backtrace always gets swallowed. Then I commented out these lines in lib/rake/application.rb

``` ruby
def standard_exception_handling
  begin
    yield
  rescue SystemExit => ex
    # Exit silently with current status
    raise
  rescue OptionParser::InvalidOption => ex
    $stderr.puts ex.message
    exit(false)
  # rescue Exception => ex
  #   # Exit with error message
  #   display_error_message(ex)
  #   exit_because_of_exception(ex)
  end
end
```

And behold, now I get a full backtrace when my task fails.

Is this by design?

**Comment by jimweirich** [comment]
I wasn't able to replicate the behavior you saw.  The latest beta version (10.1.0.beta.1) has cleaned up the backtrace suppression logic a bit and I'm wondering if any of that addressed your problem.

In any case, if you can create a short Rakefile that reproduces your issue, I would like to see it.

**Comment by jjb** [comment]
Now when I try to replicate I managed to get Ruby to segfault for some other reason I don't have time to debug now … If I encounter this bug again I'll try to make an isolated rakefile and I'll reopen this ticket.
