### ISSUE TITLE
Task's prerequisites can't generate dynamicly in task.

### ISSUE THREAD

**Issue by jtianling** [jimweirich/rake#190]
```
generated_texs = nil
task :pack_texture do
  // generate the textures
  // the code

  generated_texs = FileList[...]
end

task :png2webp => [:pack_texture] + generated_texs do

end
```

We can sure that we run task png2webp after pack_texture task, then the generated_texs have some values. But the result is that, the generated_texs alwasy be nil.
If we init the generated_texs out of any task, the result is right.

**Comment by drbrain** [comment]
This is not an issue of rake, it is an issue of your Rakefile.  `generated_texs` would be used in the following order (if not for the TypeError:
1. `generated_texs = nil`
2. `task :png2webp => [:pack_texture] + generated_texs do end`
3. `generated_texs = FileList[…]`

You need to fix your data dependency. It seems the `png2webp` task no need for `generated_texs` as the `pack_texture` task handles all the work of creating the textures and is listed as a dependency.

**Comment by damphyr** [comment]
This is because of the way rake sets and evaluates task prerequisites. In short, prerequisites are set while the dsl is parsed and before tasks are executed. So when a task is executed there is no way to change the prerequisites for this task.
In your case the file list is empty when assigned and when the task fills it the prerequisites are set.

Unfortunately changing this behaviour would introduce ambiguities in task definitions. So the patch won't make it into rake. For the full reasoning look at https://github.com/jimweirich/rake/pull/103

But there are other ways to do what you want. Check the end of the pull request for a different idiom.

**Comment by jtianling** [comment]
I have got that. The code I post here for describing the feature, I want have some prerequisites depends on the pre task, and I found I could not. Do I have some way to do that?

**Comment by michaeljbishop** [comment]
This will work as an example.

```
task :a do
  puts "b"
end

task :b do
  puts "b"
end

tasks = []

task :pack_texture do
  tasks += [:a,:b]
end

task :png2webp => :pack_texture do
  tasks.each do |name|
    Rake::Task[name].invoke
  end
end
```

If you wrote a little more about your overall goal, we might be able to give you a better answer that fits better with Rake's intention.

**Comment by jtianling** [comment]
The most important thing is that I wanted to use the rule and file task. So I will not need to generate the file twice, so I used the file task and file prerequisites. I posted the code for making sure the feature rake does. The code below describe what I really wanted.

packed_files = nil
task :pack_texture do
   #pack the file 

 packed_files = FileList[theDirOfPackedFiles]
end

task :png2webp => [:pack_texture] + packed_files

rule '.webp' => ['.png'] do |t|
  sh "cwebp -q #{quality} -quiet #{t.source} -o #{t.name}"
end

The rule is the missing things why I use the file prerequisites.I can only get the packed_files after task :pack_texture.

**Comment by jimweirich** [comment]
I'm not sure I quite followed the example, but here is something that may help you.  

The "deps.rake" task builds a file containing only dependencies.  The import statement <code>import "deps.rake"</code> will look for a task with that file name and run it, and then read the deps.rake files.  This allows deps.rake to be generated dynamically.

In the following example, I'm just creating a dependency on each .webp file for the :png2webp task.  Using import is way overkill for this, but it demonstrates the concept.

Hope this helps.

``` ruby
require 'rake/clean'

CLOBBER.include('deps.rake', 'packed/*.webp')

task :default => :png2webp

task :png2webp

PNG_FILES = FileList['packed/*.png']
WEBP_FILES = PNG_FILES.ext('webp')

task "deps.rake" do
  puts "Making Deps"
  open("deps.rake", "w") do |out|
    WEBP_FILES.each do |fn|
      out.puts "task :png2webp => ['#{fn}']"
    end
  end
end

import "deps.rake"

rule '.webp' => ['.png'] do |t|
  cp t.source, t.name
end
```

**Comment by jtianling** [comment]
Create a new file and use the import, sound a good way. I had finished the work in bad way, and will try that after the project. Thank you all.
