### ISSUE TITLE
Push 10.1 to rubygems?

### ISSUE THREAD

**Issue by contentfree** [jimweirich/rake#191]
gem can't seem to find 10.1

**Comment by jimweirich** [comment]
10.1 is not released yet.  The number is bumped in the repo in anticipation.  I put 4 digits on the version, but should have added 'beta' to make that obvious. Sorry.  I'll fix that.

**Comment by jimweirich** [comment]
FYI: the is a beta gem version 10.1.0.beta.1 published now.
