### ISSUE TITLE
Built-in clean/clobber tasks do not report failure to delete file/directory

### ISSUE THREAD

**Issue by shreyasbharath** [jimweirich/rake#199]
I just noticed this today when my clean/clobber task was not working as expected. It was not deleting a directory because I had a file inside that directory open in an editor (and it had locked the directory). 

I would expect the clean/clobber task to report that as a failure. I am using Ruby v1.9.3 and Rake v10.0.4.

**Comment by jimweirich** [comment]
Good catch.  Fixed in HEAD.
