### ISSUE TITLE
FileList and duplicates

### ISSUE THREAD

**Issue by shreyasbharath** [jimweirich/rake#202]
I ran into a rather unanticipated issue with Rake's FileList. Here's what I was doing -

I was looping through a bunch of include paths specified in a project config file like so -

```
file_list = FileList.new
project.inc_paths.each do |inc_path|
  file_list += FileList(inc_path)
end
file_list
```

Once the file list was created, I looped through it and created some objects like so -

```
file_list.each do |file|
  SomeClass.new(file)
end
```

As it turns out, there were duplicate include paths in the config file and this caused extra objects to be created (number of duplicate include paths \* SomeClass.new()).

I would expect the FileList class to remove any duplicate paths when FileList objects are added together. To me this is unintuitive behaviour so I would class it as a bug IMHO. I got around this by converting the FileList to an array and culling duplicates like so -

```
file_list = FileList.new(file_list.to_a.uniq)
```

**Comment by jimweirich** [comment]
FileLists mimic Arrays in their behavior.  So "+" is like an Array "+".  If you want to filter out duplicates, then use the "|" operator.

``` ruby
$ irb
>> require 'rake'
=> true
>> a = FileList['a','b','c']
=> ["a", "b", "c"]
>> b = FileList['a','c','d']
=> ["a", "c", "d"]
>> a + b
=> ["a", "b", "c", "a", "c", "d"]
>> a | b
=> ["a", "b", "c", "d"]
```

Also, ".uniq" and ".uniq!" are available directly on file lists.

And note that duplicates are detected only on the name, not on the resolved absolute path (which means you could still have aliases to the same file).

**Comment by shreyasbharath** [comment]
Thanks Jim, I'll try that out.
