### ISSUE TITLE
-j 1 not possible? Is there a nicer way to use "file" in a multifile way?

### ISSUE THREAD

**Issue by MarcWeber** [jimweirich/rake#205]
I'm trying to use rake for a project. Looking at the code I see that there is Task and MultiTask.
The only difference is the implementation of invoke_prerequisites.

Why can't I just do:

```
file "foo" do
end.parallel
```

?

I came up with the following code. Trying to test it I run it by "rake -j 1" - wondering why it takes less than 6 seconds. Reading up the code I find [arg, 2].max (always setting at least 2 jobs if --jobs is given. Why ? Isn't -j 1 useful for testing sometimes?

Before saying something is a bug I want to understand it first this time.

The documentation does not say that/why values less than 2 are not accepted.

Setting a default to 2 is nice, actually counting cores would be even nicer (or do something like make -j -n - looking at system load is close to perfect)

```
# encoding: UTF-8# encoding: UTF-8
require "rake"

class MultiFile < Rake::FileTask
  private
  def invoke_prerequisites(task_args, invocation_chain) # :nodoc:
    invoke_prerequisites_concurrently(task_args, invocation_chain)
  end
end

def multifile(*args, &block)
    MultiFile.define_task(*args, &block)
end

multifile "default" => ['a', 'b', 'c'] do
  sh "echo default > default"
end

%w{a b c}.each {|c|
  file c do
    sh "sleep 2; echo #{c} > #{c}"
  end
}

task :clean do
  sh "rm a b c default"
end
```

**Comment by michaeljbishop** [comment]
Just to reply quickly, passing `-m` will make every task instance a multitask (including file). As far as `-j 1` not executing in succession, I'm not quite sure yet. It does make sense that it should only execute one at a time.
Does the same happen with this code?

```
%w{a b c}.each {|c|
  file c do
    sh "sleep 2; echo #{c} > #{c}"
  end
}

file "default" => ['a', 'b', 'c'] do
  sh "echo default > default"
end
```

if you use `-m -j 1`  ?

**Comment by MarcWeber** [comment]
-m swich: Its broken by design because the user should not care about whether the Rakefile supports -j or not. The Rakefile author should care - thus he should have a way to declare this nicely.

-j > 2 and missing documentation: Have a look at this line:
https://github.com/jimweirich/rake/blob/master/lib/rake/application.rb#L412
First 2 is used if the value is invalid, then the maximum of 2 and that other value is used.
Thus -j will always be at least 2. And that doesn't make any sense to me.

**Comment by michaeljbishop** [comment]
Jim has the final word here, but to my recollection `-m` was decided as there are Rakefiles in the field already that freely mix multitask and task and intentionally (or unintentionally) depend on task execution order. Not giving the users flexibility to choose whether or not task == multitask would surely break those Rakefiles in subtle and difficult-to-debug ways.

Second point. It doesn't seem to harm anything allowing `-j 1`, but what's the use case for that? Is that not essentially a no-op? Agreed that the documentation is missing that point.

**Comment by MarcWeber** [comment]
Summary (how I think it would be perfect)
- -j1: force non multi
- -j4: use multi where the author of the Rakefile thinks it works (See Rakefile1 Rakefile2 serving as examples)
- command line -m: force multi, keep as is, but discourage its use. The user has to guess whether its ok or not. That's bad. The two examples are much better ways

Example Rakefile1:

```
file "foo" => dependencies;  sh "bar"; end.parallel
```

Example Rakefile2:

```
rake_allow_parallel_task_execution(true)
file "foo" => dependencies; sh "bar"; end
```

Use case for -j1: testing whether the buildoutput is different (eg if a build breaks). If you're using Rakefiles who were written by somebody else, how to find out whether using -m broke the build? -j1 even forces multitask to to not be "multi".
In by specific case I used it to test the rake implementation (or my understanding of rake) - then I was surprised that -j1 didn't behave the way I expected - so I assumed rake is broken (then I digged into code).

I don't want to break existing code. Maybe you agree that a solution like the one above is nicer to work with for both: authors and users.

**Comment by michaeljbishop** [comment]
User case for `-j 1`: That's a really good point. It's not a no-op since it forces `MultiTask` to behave as a `Task`.
I'm not really the guy to follow up on the viability of your other two points, but they sound good to me...

Is this a good summary?
1. Users can force sequential task execution for all tasks by specifying `-j -1`
2. Users can force parallel task execution for all tasks by specifying `-m` (deprecated) or calling a rake function `rake_allow_parallel_task_execution(true)` at the top of their rakefile.
3. Users can choose parallel task execution in specific places in their rakefile by using `MultiTask` or the proposed `Task#parallel` call.

Might be worth checking to make sure we didn't miss any valid points that might have been made in the original discussion for this feature...

http://rubyforge.org/pipermail/rake-devel/2012-October/thread.html

**Comment by jimweirich** [comment]
I'm all for lowering the limit for -j to 1, but its a bit more complicated than that.  The "j" number is actually the number of threads allowed in the thread pool and does not count the main thread. If you set -j1, you actually get a main thread and a thread pool thread.  We could internally subtract one from the "j" number (accounting for the main thread) before passing it to the for the thread pool limit (effectively allowing a thread pool count of zero).  I've tried this on a local copy of Rake and it seems to be ok. Anyways, I suspect that more investigation is needed.

**Comment by MarcWeber** [comment]
http://mawercer.de/tmp/0001-fix-j-parallel.patch
(I cannot fork and send a pull request, "repository disabled" error
message from github. I'm not sure whether this is related to their new interface)

This patch does what we talked about: It ensures -j1 does not use
parallel execution.

**Comment by jimweirich** [comment]
Applied the patch locally, will push later.  

Also I'm thinking we should bump up the default from 2.  -j2 now counts the main thread, which means there is only a single thread in the thread pool. That seems low, and since the main thread mainly waits on the futures.values, it doesn't do a lot of work.  I'm thinking bumping it the default to 4 or 8.

I would love to bump it up to the number of machine processers, but last time we looked at that, it was daunting to come up with a cross platform solution.

**Comment by MarcWeber** [comment]
> I would love to bump it up to the number of machine processers, but last time we looked at that, it was daunting to come up with a cross platform solution.
> http://stackoverflow.com/questions/891537/ruby-detect-number-of-cpus-installed

I don't think its perfect, but at least better than any default value.

If such command fails, you can still use a default (2, 4 or 8)

Eventually such implementation is not good enough to make it default,
so what about introducing "-j AUTO" ?

Docs can say that its experimental, and users have to opt-in.

I don't say use that implementation, but think about which
implementation could be stable (eg counting processor lines at
/proc/cpuinfo on linx) - so that on such platforms you can do better
than guessing. On linux nproc can be used if its available - cpus may be
"offline"

**Comment by MarcWeber** [comment]
By the way: python does have an implementation
http://docs.python.org/2/library/multiprocessing.html#multiprocessing.cpu_count
So maybe we should try to get such implementation into the threading
module of ruby?

I haven't looked at the python implementation yet.

Having something which works in 80% of cases returning 4 in all others
is better than having to guess IMHO.

What do you think?
Also how do you feel about the .parallel like interface? How would you
call it? I may try to provide an implementation then.

**Comment by jimweirich** [comment]
Regarding the .parallel suggestion:  I don't particularly like that it comes at the end of a task definition.  It seems it would be buried in a longish task.  I do like the idea of having a common way of turning both task tasks and file tasks into multitasks tho.

**Comment by jimweirich** [comment]
FYI: I have a trial version of the cpu detector at: https://gist.github.com/jimweirich/5813834

**Comment by MarcWeber** [comment]
Task.multi "foo" do .. end

?

**Comment by MarcWeber** [comment]
> CpuCounter
> There is nproc, which only counts "online cpus" (?) - however "speed
> governorns" or the like may switch cpus on, if there is enough work (?)

So I guess also counting the offline cpus is a good choice. You may want
add a small comment about this

I'd also submit this to ruby core (thread module) or such.

**Comment by MarcWeber** [comment]
This would implement the end.multi feature which "might get lost". Maybe
there are better ways. Unless somebody has a better implementation I'd
vote for this solution - even if it is easy to miss.

```
module Rake
  class Task
    def multi
      self.instance_eval {
        def invoke_prerequisites(a,b)
          invoke_prerequisites_concurrently(a,b)
        end
      }
    end
  end
end
```

**Comment by MarcWeber** [comment]
Here as patch (without test case)
http://mawercer.de/tmp/patch-dot-multi.patch
This is a reminder

**Comment by drbrain** [comment]
Like Jim I'm not very positive on the addition of #multi for the same reasons.

I think I should close this as fixed since the `-j 1` behavior is implemented.

**Comment by berlincount** [comment]
Could you please add a test for this as well? I'm still seeing -j1 causing two tasks to run in parallel in the current gem version.

**Comment by drbrain** [comment]
It should run two tasks as the changes for this pull request haven't been released. I'll check if there's a test, though.

**Comment by drbrain** [comment]
@MarcWeber I would accept a #multiplex method that worked like #namespace or #desc that made all the tasks defined within its scope or following it multitasks. This would make it easier to see.

I will close this issue once I'm sure there are -j1 tests.

**Comment by MarcWeber** [comment]
The interface of rake is broken by design (asking the user to know about whether parallel making is possible at all, and not allowing early aborting) - fixing would have been too much work for my use case which is why I created github.com/MarcWeber/rumake instead. It does exactly what I need for my use case (compiling ocaml code). I cannot take time for contributing to rake at the moment, sry.

**Comment by drbrain** [comment]
Ok, then I will close this issue.
