### ISSUE TITLE
Can't install rake 

### ISSUE THREAD

**Issue by geoffroymontel** [jimweirich/rake#210]
Hello

I installed Ruby 2.0.0-p247 and Rails 4.0.0 on a fresh Ubuntu 12.04 TLS server VM

``` bash
vagrant@dev:~$ gem -v
2.0.3
vagrant@dev:~$ bundle -v
Bundler version 1.3.5
vagrant@dev:~$ rails -v
Rails 4.0.0
vagrant@dev:~$ ruby -v
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]
```

When I do a simple

``` bash
rails new testapp
```

I get the following error

``` bash
Installing rake (10.1.0) 
Errno::EACCES: Permission denied - /usr/local/lib/ruby/gems/2.0.0/build_info/rake-10.1.0.info
An error occurred while installing rake (10.1.0), and Bundler cannot continue.
Make sure that `gem install rake -v '10.1.0'` succeeds before bundling.
```

And 

``` bash
vagrant@dev:~$ gem install rake -v '10.1.0'
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/local/lib/ruby/gems/2.0.0 directory.
```

I've never had to do any sudo to install rake before.
Do you have any idea what could be going wrong ?

Thanks !

Geoffroy

**Comment by jimweirich** [comment]
This is unlikely to be a rake issue, since rake uses the generic gem install mechanism.  My guess is that you have permissions screwed up in the gem install directory.

You can do:

```
gem env gemdir
```

to see where gems are being installed.  Check the permissions in that area to make sure everything is writable by you.

**Comment by geoffroymontel** [comment]
Thanks for your quick reply.
It seems permission are indeed broken

``` bash
vagrant@dev:~$ ls -la /usr/local/lib/ruby/gems/2.0.0/
total 28
drwxr-xr-x  7 root root 4096 Jul  8 14:16 .
drwxr-xr-x  3 root root 4096 Jul  8 14:16 ..
drwxr-xr-x  2 root root 4096 Jul  8 14:16 build_info
drwxr-xr-x  2 root root 4096 Jul  9 07:50 cache
drwxr-xr-x  2 root root 4096 Jul  8 14:16 doc
drwxr-xr-x 33 root root 4096 Jul  9 07:50 gems
drwxr-xr-x  3 root root 4096 Jul  9 07:50 specifications
```

If I do a 

``` bash
vagrant@dev:~$ sudo chmod -R 777 /usr/local/lib/ruby/gems/2.0.0/
```

Then everything is working fine, but I don't understand why I have to do that.
Anyway, I'm closing the issue !

Thanks

Geoffroy

**Comment by lee-dohm** [comment]
@geoffroymontel On many Unix systems things under `/usr/local`, being shared resources, are only writable by `root`. This is why many gem installation instructions say to do `sudo gem install foo` instead of just `gem install foo`.

**Comment by geoffroymontel** [comment]
Mmm, the problem here is that a simple `rails new testapp` is failing.
I tried again with a similar brand new Ubuntu 12.04 TLS VM with Ruby 1.9.3 and `rails new testapp` does not fail.

``` bash
vagrant@dev:~$ ruby -v
ruby 1.9.3p429 (2013-05-15 revision 40747) [x86_64-linux]
vagrant@dev:~$ gem -v
1.8.23
vagrant@dev:~$ bundle -v
Bundler version 1.3.5
vagrant@dev:~$ rails -v
Rails 4.0.0
vagrant@dev:~$ gem env gemdir
/usr/local/lib/ruby/gems/1.9.1
vagrant@dev:~$ ls -la /usr/local/lib/ruby/gems/1.9.1/
total 24
drwxrwxr-x  6 root root 4096 May 15 14:48 .
drwxrwxr-x  3 root root 4096 May 15 14:48 ..
drwxrwxr-x  2 root root 4096 Jul  9 18:24 cache
drwxrwxr-x  2 root root 4096 May 15 14:48 doc
drwxrwxr-x 48 root root 4096 Jul  9 18:24 gems
drwxrwxr-x  2 root root 4096 Jul  9 18:24 specifications
```

There must be definitely something wrong with ruby 2.0, bundler 1.3.5, rubygems 2.0.3 and Rails 4 on Linux.

**Comment by alext** [comment]
This is probably caused by bundler/bundler#2445.
