### ISSUE TITLE
Clean up Rake docs and links

### ISSUE THREAD

**Issue by jimweirich** [jimweirich/rake#218]
From an email:

Hi, Jim.

First off, thanks for rake. It’s the first build tool I’ve ever used that doesn’t fill me with a bitter mix of distrust and resentment, which is saying something.

Until a few minutes ago, I was under the delusion that 0.8.7 was the latest stable version of rake. This is probably because the first result of a Google search for rake leads to:

http://rake.rubyforge.org/

which lists 0.8.7 as the latest version. “But wait”, I said to myself, “didn’t I see rake ten-point-something on one of the servers? Is that a fork?” A quick Google search for “rake 10” led me to:

http://rake.rubyforge.org/doc/release_notes/rake-10_0_0_rdoc.html

which lists rake 0.9.0 and above. It gets better: if I click on “Home” at the top-left corner of that page, I’m taken back to the page on which 0.8.7 is the latest and greatest.

As a bonus, the default home page contains at least one bad link under “Source Repository”: it points to the GitHub repo, but inadvertently incorporates a sentence-ending period, so that it takes the user to the non-existent

https://github.com/jimweirich/rake.

RubyForge appears to be, if nothing else, consistent: if I visit

http://rubyforge.org/projects/rake

it, too, thinks that 0.8.7 is the latest version.

Since I’m not familiar with the mechanics of RubyForge, I don’t know how much control, if any, you have over the site’s presentation of rake, but I thought I’d mention the issue. It can easily leave naïve users (read: me!) with the false impression that rake is a much more sedentary project than is in fact the case, which is to everyone’s detriment.

Thanks again for this formidable tool.

Regards,
Dan

**Comment by drbrain** [comment]
Started this by adding History.txt.

**Comment by drbrain** [comment]
Improved some things to make this better with respect to history.
