### ISSUE TITLE
New behavior of "load" is incompatible

### ISSUE THREAD

**Issue by quix** [jimweirich/rake#22]
```
task :default do
end

extra = "Rakefile.extra"
File.open(extra, "w") { |f| f.puts "p SPEC" }
SPEC = 99

# OK in rake-0.8.7; error in rake-0.8.99 (uninitialized constant SPEC)
load extra

# OK in rake-0.8.99; error in rake-0.8.7 (load_rakefile not present)
load_rakefile extra
```

The change may be intentional with the new environment setup. There was no response to this question on the mailing list (http://rubyforge.org/pipermail/rake-devel/2010-June/000808.html).

**Comment by jimweirich** [comment]
Sorry for the no response on the mailing list.

This is due to the attempt to remove Rake DSL commands from the top level global namespace.

Currently I'm thinking I want to back this out and re-introduce it over a period of time. It breaks too many existing Rakefiles.
