### ISSUE TITLE
Rake should not permit nil comments to be added to a task. 

### ISSUE THREAD

**Issue by ragaskar** [jimweirich/rake#220]
Rake allows users to set nil comments via Task#comment=, but if anything calls Task#comment (such as rake -T), then an nil method exception will be raised from Task#first_sentence

IE, comment= allows you to set nil comments, but first_sentence expects comments never to be nil.

**Comment by jimweirich** [comment]
With:

``` ruby
t = task :one 
t.comment = nil
```

Running `rake -T --all` outputs the following:

```
rake one  # 
```

I don't see the problem.

**Comment by jimweirich** [comment]
Fixes have been applied to master.
