### ISSUE TITLE
Sequencing and scopes

### ISSUE THREAD

**Issue by nyarly** [jimweirich/rake#222]
If (for whatever reason) Rake sees this sequence of definitions:

```
namespace :a do
  task :one => "b:two"
end

namespace :b do
  task :two => :three

  task :three do
    puts "You'll never know that: #{meaning_of_life}"
  end
end
```

Then 'b:two' will wind up with a scope like LL() (not LL(:b)) because it was referred to first with a namespaced name.  As a result

```
rake a:one
```

will fail, because b:two will try to find :three in an empty scope, rather than in namespace b.

This seems like a bug?

**Comment by jimweirich** [comment]
As written, both a:one and b:two will fail because 'meaning_of_life' is not defined anywhere.

If I eliminate the reference to 'meaning_of_life', then both tasks seem to work for me (i.e. both will execute the b:three task).

Also, I'm not what scope you are referring to.  Is it the namespace scopes?  Or Ruby variable scope?  

An example rakefile that actually demonstrates the erroneous results would be appreciated.

Thanks.

**Comment by nyarly** [comment]
Sorry for the long delay here - I'd run into this issue, and tried to reproduce it in the issue. Seems I got the reproduction wrong, and then it took a while to hit the issue again.

The issue appears to be this: when a Task is first created, it's namespace scope is set right then to the scope of first mention. If the name used for the task refers to another namespace, that part is ignored. So:

```
namespace :a do                                                                                                                                                                 
  task :z do                                                                                                                                                                    
    p :z                                                                                                                                                                        
  end                                                                                                                                                                           

  task 'e:f' => :z                                                                                                                                                              

  namespace :e do                                                                                                                                                               
    task :g do                                                                                                                                                                  
      p :g                                                                                                                                                                      
    end                                                                                                                                                                         

    task :f => [:g] do                                                                                                                                                          
      p :f                                                                                                                                                                      
    end                                                                                                                                                                         
  end                                                                                                                                                                           
end
```

```
rake a:e:f

Don't know how to build task 'g'
```

If, task 'e:f' => :z moves to the bottom of :a, the task runs as expected (outputs g, z, f)

What happens is that task e:f creates task :f, with a scope of LL(:a). The later reference only enhances the task with a dependency on :g and the p :f action.

It's usually possible to work around this, but it's quite confusing when it happens, and it doesn't seem to be the intended design.

It think I see how to fix it, if it's agreed that it's a bug.

**Comment by nyarly** [comment]
@jimweirich Any thoughts on this? It's causing active pain for me.

**Comment by jimweirich** [comment]
Currently "task 'e:f'" is invalid format.  You are not allowed to put the namespace in the task definition.

Changing your example to the following allows it to work:

``` ruby
namespace :a do
  task :z do
    p :z
  end

  namespace :e do
    task 'f' => :z
  end

  namespace :e do
    task :g do
      p :g
    end

    task :f => [:g] do
      p :f
    end
  end
end
```

And obviously, combining the two :e namespaces would work as well.

**Comment by nyarly** [comment]
Does it make sense, then, to forbid the format? As I said: changing the sequence of definitions makes it work. And there's not clear documentation that tasks must be defined with a different naming than they're referred to.

The practical upshot is an really confusing bug, since a task that appears to exist (and does if it's defined later) doesn't get invoked. It'd be nice to either have a rejected syntax, or support for it.

I'll volunteer the PR for the fix, I'd just like to have an idea what would be best.

**Comment by jimweirich** [comment]
I'm going to close this issue and would ask you to start a new issue.  I would accept either one to make task 'e:f' report an error, or one that would actually make it work.  Your choice.
