### ISSUE TITLE
rake -T aborted

### ISSUE THREAD

**Issue by nikolaifedorov** [jimweirich/rake#223]
I use JRuby

```
> ruby -v
jruby 1.7.4 (1.9.3p392) 2013-05-16 2390d3b on Java HotSpot(TM) 64-Bit Server VM 1.7.0_21-b11 [linux-amd64]
```

When I run rake -T, i see error:

```
> rake -T
rake aborted!
undefined method `split' for nil:NilClass
org/jruby/RubyArray.java:2417:in `map'
org/jruby/RubyArray.java:2473:in `select'
org/jruby/RubyKernel.java:1073:in `load'
(See full trace by running task with --trace)
```

**Comment by damphyr** [comment]
Things like this happen when you have code in your Rakefile that runs outside of a task action etc.
You're actually providing very little information about the problem. Can you post a Rakefile that reproduces your problem and maybe also the stacktrace with --trace?

**Comment by jimweirich** [comment]
Thanks. Changes have been applied to master.
