### ISSUE TITLE
Rake not flushing stdout when used with a pipe

### ISSUE THREAD

**Issue by trans** [jimweirich/rake#237]
This issue derives from pry/pry#1011 via rails/rails#12960. To summarize, there is a problem with stdout not being flushed when using a pipe on a rake task. I had thought the problem had something to do with Pry, then Rails, but now it looks to be simply an issue with Rake.

If we add a rake task:

``` ruby
desc "try it"
task :try do
  puts "Just some example."
  sleep 5
  puts "Now we are here."
end
```

And create a dummy-pipe executable:

``` bash
#!/usr/bin/env ruby
while line = $stdin.gets
  $stdout.print line
end
```

Then when we run `rake try` is behaves as expected. But if we run `rake try | dummy-pipe` then is doesn't print the first line immediately. Instead it sleeps first and then prints both lines all at once.

**Comment by jimweirich** [comment]
Replace the Rake file with this:

```
puts "Just some example."
sleep 5
puts "Now we are here."
```

And you will see the same behavior. It's not a Rake issue, and not really a Ruby issue either, but just how stdio works in a Unix system.

You can add a STDOUT.flush after the first print, or set STDOUT.sync = true at the top of either the Rakefile or the example and you will get the behavior you want.

**Comment by trans** [comment]
Ah, thanks. That's what I thought at first but my original attempt at setting sync didn't work which led me to think it must have something to do with some other dependency. Turns out I just had to move the call to be after the initialization of `Minitest::StatisticsReporter`, rather than before, and it worked. Sorry for the noise.
