### ISSUE TITLE
Bug in can_detect_signals? in test_rake_functional.rb

### ISSUE THREAD

**Issue by snaury** [jimweirich/rake#243]
Originally reported here:

http://bugs.ruby-lang.org/issues/9211

But maybe it's more appropriate to be here.

In function can_detect_signals? in file test_rake_functional.rb ruby is spawned incorrectly. There should be multiple parameters in a system call, since otherwise ruby is spawned from a shell, status ends up in a shell, and shell is not killed with a signal (obviously). Currently this causes test_signal_propagation_in_tests to be skipped on Linux. Attached patch fixes the problem, test is no longer skipped and now passes on Linux.

The fix is simple:

``` diff
diff --git a/test/rake/test_rake_functional.rb b/test/rake/test_rake_functional.rb
index f2ce2f7..c5d832f 100644
--- a/test/rake/test_rake_functional.rb
+++ b/test/rake/test_rake_functional.rb
@@ -414,7 +414,7 @@ class TestRakeFunctional < Rake::TestCase
   end

   def can_detect_signals?
-    system "ruby -e 'Process.kill \"TERM\", $$'"
+    system RUBY, '-e', 'Process.kill "TERM", $$'
     status = $?
     if @verbose
       puts "    SIG status = #{$?.inspect}"
```

**Comment by tmm1** [comment]
:+1:
