### ISSUE TITLE
runtest still using Test::Unit, is this desired?

### ISSUE THREAD

**Issue by bbonamin** [jimweirich/rake#244]
Hey folks, 

Some colleagues are using runtest.rb to run tests but they've found the need to rewrite this file in order to use minitest like the rest of the project. Is the fact that runtest still uses Test::Unit intended or a matter of legacy for a file that has not been updated in a long time? 
https://github.com/jimweirich/rake/blob/master/lib/rake/runtest.rb

If the answer is the second, I can submit a PR

**Comment by drbrain** [comment]
Ruby 1.9 still has a Test::Unit but I will need to investigate to determine if this is still proper.

**Comment by drbrain** [comment]
I think Rake::TestTask should be used instead of Rake.run_tests.  Rake::TestTask works with minitest fine because it uses a subprocess to run the tests instead of in-process.

Changing Rake.run_tests would be backward incompatible.  I'm going to mark it for removal in rake 11.

**Comment by bbonamin** [comment]
Thanks for the update! I'll pass the info along to my colleagues
