### ISSUE TITLE
0.9.0.beta1: rspec task: uninitialized constant RSpec::Core::RakeTask::RakeFileUtils

### ISSUE THREAD

**Issue by elisehuard** [jimweirich/rake#25]
This may be more the fact that Rspec hasn't adapted to the 0.9.0 beta version yet, but when running rake spec
uninitialized constant RSpec::Core::RakeTask::RakeFileUtils

This isn't a problem with the 0.8.7 which we were using so far.

**Comment by jimweirich** [comment]
I've been using rake 0.9.x (beta and otherwise) on rspec'ed projects without problem.  Can you give me a small project that reproduces the problem.

**Comment by drbrain** [comment]
Closing due to lack of feedback.
