### ISSUE TITLE
Ruby 2.0.0-p353 + rake test = fail

### ISSUE THREAD

**Issue by NathanZook** [jimweirich/rake#258]
rake-10.1.1/lib/rake/runtest.rb line 12 expects the current working directory to effectively be in the load path.  Presumably, this used to work.

Related to #244.

**Comment by drbrain** [comment]
How do I reproduce this?

**Comment by drbrain** [comment]
After reviewing #244 the best way to create a test task is using Rake::TestTask not Rake.run_tests.  I will reject this issue along with #244.
