### ISSUE TITLE
Shouldn't we be able to access the namespace path?

### ISSUE THREAD

**Issue by jsm** [jimweirich/rake#263]
I'm currently able to do so with

```
namespace.instance_variable_get("@scope").path
```

but I feel like this should be a method of the NameSpace class.

**Comment by drbrain** [comment]
Curious, what are you doing with the scope?

**Comment by jsm** [comment]
I was actually trying to use it to call the "default task" for a namespace, since they're not declared within the actual namespace.

I ended up making a slightly hacky method called "default_task" which is able to define a default task within the current namespace. Here it is if you're interested: https://gist.github.com/jsm/9923760

Thanks for the commit!

**Comment by drbrain** [comment]
Clever, I understand your motivation. It almost seems like your script should be a method on Rake::NameSpace.
