### ISSUE TITLE
rules do not recieve arguments

### ISSUE THREAD

**Issue by nukemberg** [jimweirich/rake#27]
<pre><code>require 'rake'

desc "test"
task :test, [:arg1] => ['test.txt', 'test.csv'] do |t, args|
  puts t.name + ": " + args.inspect
end

file "test.txt", [:arg1] do |t, args|
  puts t.name + ": " + args.inspect
end

rule ".csv", [:arg1] do |t, args|
  puts t.name + ": " + args.inspect
end
</code></pre>
running this with <pre>rake -v -t test[somearg]</pre> yields:
<pre>
** Invoke test (first_time)
** Invoke test.txt (first_time)
** Execute test.txt
test.txt: {:arg1=>"somearg"}
** Invoke test.csv (first_time)
** Execute test.csv
test.csv: {}
** Execute test
test: {:arg1=>"somearg"}
</pre>

Since rule synthesize file tasks, i would expect the generated tasks to behave the same as file task, including argument handling. This behavior is due to the way <tt>resolve_args</tt> is called in <tt>create_rule</tt> function (lib/rake/task_manager.rb):
      def create_rule(*args, &block)
        pattern, _, deps = resolve_args(args)
        pattern = Regexp.new(Regexp.quote(pattern) + '$') if String === pattern
        @rules << [pattern, deps, block]
      end
Arguments are returned to _ and thrown away.

**Comment by jimweirich** [comment]
I'm trying to think if there is a good reason for not passing args to rules.  I will ponder more on this.

**Comment by quix** [comment]
avishai-ish-shalom, were you aware that arguments are still passed to rules? Replace your rule with

```
rule ".csv", [:arg1] do |t, args|
  puts t.name + "[:arg1]: " + args[:arg1]
end
```

Output:

```
test.txt: {:arg1=>"somearg"}
test.csv[:arg1]: somearg
test: {:arg1=>"somearg"}
```

**Comment by nukemberg** [comment]
weird! how come args[:args1] works but inspect fails? i need to dig into this.

**Comment by quix** [comment]
The default inspect does not walk the parents. A deep_inspect method could do so (https://github.com/quix/rake/commit/84df62), but it's unclear whether this should be the default.

```
rule ".csv", [:arg1] do |t, args|
  puts t.name + ": " + args.deep_inspect
end
```

**Comment by jimweirich** [comment]
looks like this is solved.

**Comment by Shumakriss** [comment]
I know this is ancient but... Is this possibly an issue in earlier versions? 0.9.2.2 for example?
