### ISSUE TITLE
Ressurecting Jim's Website - onestepback.org?

### ISSUE THREAD

**Issue by mbishop-fiksu** [jimweirich/rake#288]
I don't know where else to put this question exactly, but I noticed that http://onestepback.org was down. Are there any plans to keep the content from that alive? Did he check it into source control anywhere?

**Comment by Falkor** [comment]
The same for http://rake.rubyforge.org/ ...

**Comment by rdlugosz** [comment]
I think the best option for this is the [Wayback Machine](http://web.archive.org/web/*/onestepback.org). To my knowledge, the source to this site was not in his GitHub account (it predated GH and I think he maintained it in a private repository somewhere).

**Comment by pombredanne** [comment]
just in case some of you did not notice: Jim Weirich is no more. RIP.  http://en.wikipedia.org/wiki/Jim_Weirich

**Comment by telemachus** [comment]
I just came to post an issue about this. I'm aware that Jim has passed away. I wonder, however, if it might not be possible to reconstruct some of the wonderful material that used to be on his site? (Someone in his family might be willing to provide the source of the old site, perhaps?) Failing that, it does seem like the links that are 404 should be removed.

I would be happy to help do some of the work for this, but I'm not sure where or how to begin. I really would love to see Jim's material about Rake preserved (just as, for example why's work was preserved).

**Comment by rdlugosz** [comment]
Hi @telemachus - Unfortunately, the source for Jim's site was not stored on GitHub and I don't think it was ever in a public repository. The Wayback Machine link I listed above is a reasonable alternative for repointing links and getting access to what used to be online.

**Comment by drbrain** [comment]
I have contacted people at neo.com and asked them to come here and comment on this issue.

Since I cannot do anything to resurrect the website and it is not a rake issue I will close this.
