### ISSUE TITLE
desc assigns desc to a prerequisite

### ISSUE THREAD

**Issue by dfherr** [jimweirich/rake#290]
desc does not always assign it's description to the task specified after it, but to the first rake task finished after calling description.

This causes false descriptions if you dynamically generate rake tasks with methods called in prerequisites.

An example:

``` ruby
def make_tasks
 name = "dynamicTest"
 Rake::Task.define_task(name)

 name
end

desc "Test rake task"
task "Test" => make_tasks
```

will cause rake to add the description to the dynamicTest task instead of the Test task. This behavior is very confusing.
I don't know if this should actually get fixed or an explanation of the problem in the desc method would be more appropiate. Simply assigning desc before the prerequisites get evaluated would probably solve the issue.

Using the following order and methods instead is a good workaround:

``` ruby
task "Test" => make_tasks
Rake::Task["Test"].add_description("description text") 
```

**Comment by ipmsteven** [comment]
I have a similar issue when using desc to assign description to the TestTask specified after it. 

It seems that in this commit 8934145d8c686d49de4e85a37429dc38d1af6472 
The assigned description is override
(https://github.com/jimweirich/rake/commit/8934145d8c686d49de4e85a37429dc38d1af6472?diff=split#diff-a63806105545e64fee74722586ea61c5R17)

However, maybe 

``` ruby
desc "Run xxx tests"
Rake::TestTask.new("name" => "deps") do |t|
  t.libs << "test"
  t.libs << "test/xxx"
  t.pattern = 'test/xxx/**/*_test.rb'
end
```

is not a best practice to assign description for test task, we should use

``` ruby
Rake::TestTask.new("name" => "deps") do |t|
  t.libs << "test"
  t.libs << "test/xxx"
  t.pattern = 'test/xxx/**/*_test.rb'
  t.description = "Run xxx tests"
end
```

instead?

any thoughts? @dfherr @Tonkpils @shime

**Comment by drbrain** [comment]
@dfherr I don't consider this a bug as the documentation says "Describes the next rake task" and that is what it is doing as `make_tasks` contains the next task definition.

Since you are hiding task definition behind a method maybe you want to use `import` instead?

Changing only your example:

``` ruby
def make_tasks
 name = "dynamicTest"
 Rake::Task.define_task(name)

 task "Test" => name
end

desc "Test rake task"
task "Test"

make_tasks
```

**Comment by drbrain** [comment]
@ipmsteven: `t.description = "Run xxx tests"` is the best practice.
