### ISSUE TITLE
Support for out-of-source builds

### ISSUE THREAD

**Issue by elfring** [jimweirich/rake#294]
How do you think about to benefit from [parallel build trees](http://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html) also for your software?
Would you like to [support out-of-source](http://cmake.org/Wiki/CMake_FAQ#What_is_an_.22out-of-source.22_build.3F) ([VPATH](http://www.gnu.org/software/make/manual/html_node/General-Search.html)) builds?

**Comment by drbrain** [comment]
make itself does not know about out-of-source builds.  This is a product of autotools and its associated tooling.

As far as I know rake supports out-of-source builds just as well as make.  If you try it and have difficulties please open new issues.

**Comment by elfring** [comment]
How can the corresponding output directory be configured for an out-of-source build with Rake?

**Comment by damphyr** [comment]
The answer as always is "it depends".
What are you building? Are you using a C toolchain? There's a few things to do, e.g. make sure the command lines for the tools all explicitly set the output filename. 

Check out [gaudi](https://github.com/damphyr/gaudi) if you want to see something built on rake that does exactly what you're asking for for C/C++ toolchains. (disclosure: gaudi is my own construct so I'm biased)

**Comment by elfring** [comment]
Which variable (or Ruby class) does manage the output directory for an out-of-source build with the Rake software?

**Comment by damphyr** [comment]
Which out-of-the-box tasks are you using? What does your build look like? 
There isn't some magic setting or variable to set to make build artefacts land somewhere, you have to code this in your tasks.

**Comment by elfring** [comment]
I would expect that there is a default output directory managed from the specification of a variable like `VPATH` (or `PATH_OUT` for example).
How would this configuration detail work together with the Rake build system?
