### ISSUE TITLE
Rake uses stderr inappropriately

### ISSUE THREAD

**Issue by patch0** [jimweirich/rake#3]
Rake 0.8.7 sending normal messages to stderr is broken behaviour.

```
# Send the message to the default rake output (which is $stderr).
def rake_output_message(message)
  $stderr.puts(message)
end
private :rake_output_message
```

Surely it should be sending that to stdout instead?  The problem being
this makes it hard to distinguish between normal output and actual error
output, since everything goes to stderr.

**Comment by jimweirich** [comment]
Yes, I agree.  I have no idea why I chose to use stderr here.  Fortunately it is an easy fix.

Issue moved to Pivotal Tracker: http://www.pivotaltracker.com/story/show/5227189

**Comment by aef** [comment]
This is still a problem in 0.9.2, in lib/rake/file_utils_ext.rb line 129.
