### ISSUE TITLE
Silencing directory announcements should not be as hard as it is

### ISSUE THREAD

**Issue by kagminjeong** [jimweirich/rake#30]
Currently rake prints which directory the rakefile it processes is by default.

This output can be turned off by an option. However this is suboptimal because:
1. Executing rake from a rake task means the new invocations print everything again.
2. Every single rake invocation must be edited to give it the option. If we are talking about e.g. crontabs this is a fair amount of work.
3. Sometimes third party software invokes rake, silencing it involves patching that software.

I cannot recall a situation where I had a problem that was solved by this output. It seems to be somewhere between ignorable noise and a major annoyance depending on the circumstance.

Suggested solutions to this are:
1. Make silence the default. If a user is having an issue requiring them to know what rakefile is being executed, provide an option to turn the announcements back on.
2. Make it so that the silence can be requested via an environment variable, which can be then set in crontab, profile, ENV, etc.

If option 1 is elected, please don't break all rake-invoking scripts ever written by removing the current option that silences the announcement. Make it a no-op for at least the next 3 years.

**Comment by drbrain** [comment]
Did you check rake trunk?

Currently the directory is not printed unless rake must cd to the proper directory.

Additionally the directory is printed on $stderr now.
