### ISSUE TITLE
Rake tasks fail with 0.9.0 gem

### ISSUE THREAD

**Issue by schmickie** [jimweirich/rake#32]
We set up a new environment today, so the bundle install grabbed the newly released 0.9.0 version of the rake gem. We had of course been using 0.8.7 prior to that with no issues. With the 0.9.0 version of the gem, our rake tasks no longer run successfully, but instead give the following stack trace.

https://gist.github.com/983447

**Comment by schmickie** [comment]
Some comments regarding this issue and possible solutions have been made on the gist, so please follow the link to see them.

**Comment by rounders** [comment]
I'm seeing this same issue when using spree commerce and also with using refineryCMS.  Reverting to 0.8.7 works.

**Comment by bilts** [comment]
This seems to be an issue with other libraries relying on Rake's methods being available throughout the application.  As of 0.9.0, they're only available at the top level.

You can fix this in a couple of ways.  require 'rake/dsl'  should pretty much fix the problem application-wide.  That's kind of the nuclear option, though.  For a more confined solution, you can extend Rake::DSL on an individual class, to have access to to the tasks as expected, or you can namespace your method calls.

This is a problem in Rails 3.x.  I've submitted a [pull request](https://github.com/rails/rails/pull/1174) to fix it there.  It seems like this change to rake is the right thing to do, but that a lot of applications were depending on rake doing the wrong thing.

**Comment by quix** [comment]
@bilts -- FYI "require 'rake/dsl'" wasn't intended to do that (see #35).

**Comment by schmickie** [comment]
I was trying to reproduce the case in which I got this stack trace today so I could add more feedback. However, the original scenario was supposedly that I installed the 0.9.0 gem and the old built-in 0.8.7 binary still existed and was being loaded, then trying to load 0.9.0 gem files. I found when I installed the 0.9.0 version of the gem just now, it overrode the old 0.8.7 version of the binary, and I no longer get the above stack trace, so I'm not sure how I originally got it to happen. 

That being said, I get a new stack trace. I was going to open a new bug, but I guess it still falls under the heading of this bug, so here is the new stack trace:

https://gist.github.com/987134

**Comment by quix** [comment]
@schmickie, that looks like #33.

**Comment by schmickie** [comment]
So, #33 is closed, although the proposed solutions don't work for me. I commented on the issue, but was unable to re-open it. Should I start a new issue?

**Comment by schmickie** [comment]
I figured it out using the hints on #33. Closing out this issue.
