### ISSUE TITLE
0.9.0  causes bundler fail on Gem build

### ISSUE THREAD

**Issue by JoshMcKin** [jimweirich/rake#34]
I was suffering from this problem https://github.com/jimweirich/rake/issues/32 but found this work around http://stackoverflow.com/questions/5287121/undefined-method-task-using-rake-0-9-0-beta-4 

Unfortunately, even with the work around for custom rake tasks when I try to build my engine gem with bundler I now get this error: https://gist.github.com/983763

Thanks,
Josh

**Comment by fourcolors** [comment]
I'm having the exact same problem.

**Comment by quix** [comment]
From the backtrace it would appear that this is needed:

```
module Bundler
  class GemHelper
    include Rake::DSL if defined? Rake::DSL
  end
end
```

If other classes use 'desc', 'task', etc. then include Rake::DSL in them too.

**Comment by quix** [comment]
Bundler already handles this with the nuclear option of a top-level <code>include Rake::DSL</code> (https://github.com/carlhuda/bundler/commit/6c3123). The purpose Rake::DSL seems to have been misunderstood there.

**Comment by crawlik** [comment]
Run into the same issue. Revert to rake 0.8.7 solved the problem.

**Comment by jimweirich** [comment]
Rake 0.9.1 should be solving these problems.
