### ISSUE TITLE
Rake fails with undefined method `task' for #<appname::Application:whatever>

### ISSUE THREAD

**Issue by byrnejb** [jimweirich/rake#41]
Ruby-1.8.7
Rake-0.9.0
Rails-3.0.7
Cucumber-0.10.3

In rails root:

<pre>
 $ rake cucumber --trace
Using AdapterExtensions
rake aborted!
undefined method `task' for #<Proforma::Application:0x2b9e2c343cf8>
/home/byrnejb/.rvm/gems/ruby-1.8.7-p334/gems/railties-3.0.7/lib/rails/application.rb:215:in `initialize_tasks'
/home/byrnejb/.rvm/gems/ruby-1.8.7-p334/gems/railties-3.0.7/lib/rails/application.rb:139:in `load_tasks'
/home/byrnejb/.rvm/gems/ruby-1.8.7-p334/gems/railties-3.0.7/lib/rails/application.rb:77:in `send'
/home/byrnejb/.rvm/gems/ruby-1.8.7-p334/gems/railties-3.0.7/lib/rails/application.rb:77:in `method_missing'
/home/byrnejb/Software/Development/Projects/proforma.rails3/Rakefile:8
/home/byrnejb/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.9.0/lib/rake/rake_module.rb:25:in `load'
/home/byrnejb/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.9.0/lib/rake/rake_module.rb:25:in `load_rakefile'
/home/byrnejb/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.9.0/lib/rake/application.rb:495:in `raw_load_rakefile'
/home/byrnejb/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.9.0/lib/rake/application.rb:78:in `load_rakefile'
/home/byrnejb/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.9.0/lib/rake/application.rb:129:in `standard_exception_handling'
/home/byrnejb/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.9.0/lib/rake/application.rb:77:in `load_rakefile'
/home/byrnejb/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.9.0/lib/rake/application.rb:61:in `run'
/home/byrnejb/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.9.0/lib/rake/application.rb:129:in `standard_exception_handling'
/home/byrnejb/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.9.0/lib/rake/application.rb:59:in `run'
/home/byrnejb/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.9.0/bin/rake:31
/home/byrnejb/.rvm/gems/ruby-1.8.7-p334/bin/rake:19:in `load'
/home/byrnejb/.rvm/gems/ruby-1.8.7-p334/bin/rake:19
 </pre>

I do not get this exception with rake-0.8.7.

**Comment by quix** [comment]
Try #33.

**Comment by jimweirich** [comment]
Rake 0.9.1 has added deprecation warnings for the global DSL methods.  The old rakefiles will now run, but will generate warnings.
