### ISSUE TITLE
Rake 0.9.1 and Rails 3.1 

### ISSUE THREAD

**Issue by tpletcher** [jimweirich/rake#46]
Hate to revisit a closed issue but I am still getting the "uninitialized constant Rake::DSL" error on a vanilla rails3.1rc1 app. I have tried the workarounds in #33 from jim and also this patch in rakefile:

module ::YourApplicationName
  class Application
    include Rake::DSL
  end
end

module ::RakeFileUtils
  extend Rake::FileUtilsExt
end

but still no luck. i am using rvm with gemsets so pretty standard enviro set-up. any help appreciated...

**Comment by jimweirich** [comment]
Some Ideas:

(1) verify that you are really using Rake 0.9.x.  Rake::DSL doesn't exist prior to that.
(2) change the include line to be:  include Rake::DSL if defined? Rake::DSL.  This allows backwards compatibility with older versions of rake.
(3) If this is not being loaded directly by Rake, then it could possibly be loading this before the rake library is loaded.  Add a require 'rake' to the top of the file to handle this.

**Comment by tpletcher** [comment]
Thanks Jim. it was actually issue number one, as 0.8.7 is loaded with ruby and was being called by the base rake db:xxxxx command. using bundle exec rake db:xxxxxx.

very much appreciate the quick response!

cheers,

tim
