### ISSUE TITLE
DeprecatedObjectDSL doesn't behave like the API from 0.8.7

### ISSUE THREAD

**Issue by jstorimer** [jimweirich/rake#55]
In Rake 0.8.7 the DSL methods were defined right on the `main:Object` in lib/rake.rb. In 0.9.2 there is a compatibility layer for that stuff in Rake::DSL::DeprecatedObjectDSL. This is a module that gets included into the `main:Object`. These two approaches yield slightly different results.

Without knowing too much about Ruby internals I can say that defining methods right on the `main:Object` makes them available at the top level, like in a .rake file, but it doesn't make them available on Object itself, ie. to classes that inherit from Object.

By including a module at the top level you do make those methods available to any children of Object. This is subtlely breaking my application when using Rake. I have an ActiveRecord model with an attribute called 'namespace'. Rails uses method_missing to look up attributes when they are first accessed. If Rake has been loaded (via rake_test_loader for instance) and I attempt to access my 'namespace' attribute I'm instead intercepted by the namespace method that has been included into Object by Rake::DSL::DeprecatedObjectMethods (https://github.com/jimweirich/rake/blob/master/lib/rake/dsl_definition.rb#L167).

The obvious solution seemed to be to restore the previous behaviour and define these deprecated methods right on `main:Object` (https://github.com/jstorimer/rake/commit/eab9ad4612d14c1ea5476fe3932253a1a8ee7aff). Unfortunately this causes lots of deprecation warnings in the test suite and causes the two tests that test the deprecated DSL to fail.

On a side note, the two tests that test the deprecated DSL actually won't pass in Rake 0.8.7. What are they testing? https://github.com/jimweirich/rake/blob/master/test/test_rake_dsl.rb#L36-72

I'm sure that with the DeprecatedDSL stuff there was no intention of colliding with stuff in other classes, so what's the best approach here? This is a simple test case to reproduce the issue: https://github.com/jstorimer/rake/commit/2ea9f01a5573504051f44d16694e0f45fb48c0a7. It throws a LocalJumpError when ran against the current rake master.

**Comment by ahoward** [comment]
the tests are seeing if calling those methods prints warning on stderr.

the best way to mix methods into the top level is not adding them to main, rather

<code>
module Kernel
private
  def globally_available_but_does_not_pollute_Object
  end
end
</code>

**Comment by quix** [comment]
The <code>--reduce-compat</code> option (#63) should fix this.

ahoward, Jim didn't want the Rake DSL to be available everywhere.

**Comment by quix** [comment]
@jstorimer, I tried your code but I wasn't able to reproduce your problem. Since the two tests you deleted work for me, there must be some other issue you encountered.

I assume the mere presence of the global DSL methods is causing your problem, in which case --reduce-compat should solve it.

Whether methods are defined in Object or included into Object, method_missing is not affected.

```
if ARGV.shift == "inc"
  module Bar
    def foo
      "Bar#foo"
    end
  end
  include Bar 
else
  def foo
    "Object#foo"
  end
end

class Check
  def run
    foo
  end
  def method_missing(meth, *)
    raise "method_missing called"
  end
end

p Check.new.run
```

**Comment by jimweirich** [comment]
I suspect this was a problem with a pre-0.9.2 version of Rake.  Can you try it with the most recent version and see if you still have issues.

Thanks.

**Comment by lukeredpath** [comment]
Hi Jim,

I'm having the same problem, using Rake 0.9.2.

I'm trying to define a method called install on one of my models (actually, it's being defined by the state_machine gem) but when I try and call it it fails as install is a private method declared in Object. The output of Object.method(:install) yields:

```
ruby-1.9.2-p180 :001 > Object.method(:install)
 => #<Method: Class(Rake::DeprecatedObjectDSL)#install> 
```

**Comment by jimweirich** [comment]
Post 0.9.x rake version will remove the top level deprecation warnings entirely.
