### ISSUE TITLE
Adhere to RubyGems version numbering policy!

### ISSUE THREAD

**Issue by sunaku** [jimweirich/rake#59]
@drbrain and @jimweirich,

I am thoroughly disappointed that the Rake 0.9 release contained incompatible changes.  If only you had adhered to the [RubyGems rational versioning policy](http://docs.rubygems.org/read/chapter/7), you would have numbered that release as 1.0. By doing so, you would have saved the Ruby community from needless agony when people innocently ran `gem update`, trusting RubyGems (and you!) that Rake 0.9 was indeed a minor feature release that _did not_ contain any incompatible changes.

Please let this be a lesson going forward for Rake and all other gems you create.  And please use your fame/clout to help raise awareness of the **RubyGems' rational versioning policy** so that this debacle can be avoided in the future.

Thanks for your consideration.

**Comment by drbrain** [comment]
This is not up to me.

**Comment by matthijsgroen** [comment]
+1

**Comment by jimweirich** [comment]
So Noted.
