### ISSUE TITLE
a bump to ruby 1.9.2p290 make rake failed

### ISSUE THREAD

**Issue by nguyenchiencong** [jimweirich/rake#60]
uninitialized constant Rake::DSL

**Comment by nguyenchiencong** [comment]
This kind of solution temporarily solved the problem
http://stackoverflow.com/questions/6181312/how-to-fix-the-uninitialized-constant-rakedsl-problem-on-heroku

**Comment by drbrain** [comment]
There's not enough information here for me to help you with this bug report.

I'll need at least a stack trace and possibly a portion of your Rakefile.

Also, please look at the release notes for Rake 0.9.x, you may need to include Rake::DSL in your application depending upon how you're using Rake.

**Comment by nguyenchiencong** [comment]
I went back to 1.9.2p180 for now, I'll post the stack trace tomorrow when I'll bump up to 1.9.2p290 again (but this time on my VM with RVM).

**Comment by nguyenchiencong** [comment]
No problem in fact, by installing ruby 1.9.2p290, it just reinstall rake 0.8.7. A clean :
- sudo gem uninstall rake
- sudo gem install rake
  will do.

cheers

**Comment by drbrain** [comment]
Yes, you needed to reinstall rake as there were mixed versions in use.  The stack trace shows both the core version of rake and the remote gem of rake being used at the same time.
