### ISSUE TITLE
test/test_rake_directory_task.rb is wrong

### ISSUE THREAD

**Issue by unak** [jimweirich/rake#61]
I found one failure in MRI trunk on Windows.
Isn't this what you want to test?
# Index: test_rake_directory_task.rb

--- test_rake_directory_task.rb (revision 32668)
+++ test_rake_directory_task.rb (working copy)
@@ -29,8 +29,9 @@ class TestRakeDirectoryTask < Rake::Test
     def test_directory_win32
       desc "WIN32 DESC"
       directory 'c:/a/b/c'
-      assert_equal FileCreationTask, Task['c:'].class
-      assert_equal FileTask, Task['c:'].class
     assert_equal FileCreationTask, Task['c:/a'].class
-      assert_equal FileCreationTask, Task['c:/a/b'].class
     assert_equal FileCreationTask, Task['c:/a/b/c'].class
     assert_nil             Task['c:/'].comment
     assert_equal "WIN32 DESC",   Task['c:/a/b/c'].comment

**Comment by jimweirich** [comment]
Can I get a clarification on this.  Is this an observed failure in the field on a windows box, or do you have a reason to expected the class of the "C:" task to be FileTask rather than FileCreationTask?

I don't have access to a windows box to verify check this.

**Comment by unak** [comment]
Because the result is FileTask :)

"C:" means "drive C" or "current directory of drive C", and we can not create a drive or current directory.
So, I expected that the result was correct and the test was wrong.

**Comment by jimweirich** [comment]
Removed the part of the test that was creating directories in C:
