### ISSUE TITLE
::Task is returned as Rake::Task and does not lazy load Task model in Rails app

### ISSUE THREAD

**Issue by rsim** [jimweirich/rake#7]
We have issue that in our Rails application we have Task model and Rails does lazy loading of models which means that it is not loaded initially when loading application.

If "rake" is required in Rails application then it defines Module#const_missing method
http://github.com/jimweirich/rake/blob/master/lib/rake/ext/module.rb#L42-46
which returns Rake::Task for global ::Task constant (together with warning message) and as a result Task model class is not loaded by ActiveSupport.

If global Task constant is deprecated already for long time then I suggest to remove this const_missing functionality as it gives this unexpected behavior for Task model (which might be quite frequent model name in Rails applications).

**Comment by gucki** [comment]
+1

**Comment by tma** [comment]
+1

**Comment by agileapplications** [comment]
+1

**Comment by jimweirich** [comment]
Good point.  We will remove the warnings for these global level constants.

**Comment by eendeego** [comment]
+1 - Also got hit by this.

**Comment by quix** [comment]
The <code>--reduce-compat</code> option (#63) should solve this. Try it out, if you wish.

**Comment by ilya-manin** [comment]
+100500

**Comment by evserykh** [comment]
+1

**Comment by dmitry-a-l** [comment]
+1

**Comment by qrush** [comment]
Solution here in the interim...

In your Gemfile:

`gem 'rake', '0.9.3.beta.1'`

And on the very top of your `config/environment.rb` (this is Rails 2.3):

``` ruby
module Rake
  REDUCE_COMPAT = true
end
```

**Comment by bitencode** [comment]
Affecting one of my apps also. :(  It used to work, not sure when it broke, but on Rails 3.2.x and Rake 0.9.2.2 I cannot get Rails to load my Task model anymore, it always goes for Rake::Task.  Been pulling my hair out trying to get my app to run again...
+100

**Comment by jimweirich** [comment]
Post 0.9.x versions of rake will remove the top level deprecations entirely.
