### ISSUE TITLE
Include ability to set description in Rake::TestTask

### ISSUE THREAD

**Issue by rosenfeld** [jimweirich/rake#71]
Could you please support custom descriptions in TestTask tasks?

**Comment by geeksam** [comment]
I've just arrived at this issue by searching for documentation on how to do this very thing (as "Run tests for unit" sounds awkward). I guess that's a +1. (=

**Comment by szimek** [comment]
+1

**Comment by oby1** [comment]
:+1:

**Comment by zenspider** [comment]
Workaround:

``` ruby
Rake::TestTask.new(:uber)

task(:uber).full_comment.replace "I'll do whatever I want!"
```

**Comment by jimweirich** [comment]
Task#clear now clears out the description as well as the prerequisites and actions.  You can also directly call Task#clear_comments to only clear out the comments.

**Comment by shime** [comment]
@zenspider I'm afraid that will only replace the returned string:

``` ruby
Rake::TestTask.new(:uber)

task(:uber).full_comment.replace "I'll do whatever I want!"

task(:uber).full_comment # => Run tests for uber
```

@jimweirich not sure why this is closed since `Task#clear` and `Task#clear_comments` are meant for clearing only. Test task descriptions are currently not customizable.

Let's push a **PR** in your direction...

**Comment by Tonkpils** [comment]
@shime let me know how I can be of help :+1:
