### ISSUE TITLE
-tT and -Tt are not equivalent

### ISSUE THREAD

**Issue by p** [jimweirich/rake#73]
Looks like whether -t is respected depends on the order of arguments:

<pre>
reactor% rake -Tt
rake aborted!
no such file to load -- rubygems/package_task

(See full trace by running task with --trace)

reactor% rake -tT
rake aborted!
no such file to load -- rubygems/package_task
/home/gemowner/pkg/lib/rake/extensiontask.rb:4:in `require'
/home/gemowner/pkg/lib/rake/extensiontask.rb:4
./tasks/compile.rake:4:in `require'
./tasks/compile.rake:4
/home/pie/apps/yajl-ruby/Rakefile:2:in `load'
/home/pie/apps/yajl-ruby/Rakefile:2
/home/pie/apps/yajl-ruby/Rakefile:2:in `each'
/home/pie/apps/yajl-ruby/Rakefile:2
/home/gemowner/pkg/lib/rake/rake_module.rb:25:in `load'
/home/gemowner/pkg/lib/rake/rake_module.rb:25:in `load_rakefile'
/home/gemowner/pkg/lib/rake/application.rb:495:in `raw_load_rakefile'
/home/gemowner/pkg/lib/rake/application.rb:78:in `load_rakefile'
/home/gemowner/pkg/lib/rake/application.rb:129:in `standard_exception_handling'
/home/gemowner/pkg/lib/rake/application.rb:77:in `load_rakefile'
/home/gemowner/pkg/lib/rake/application.rb:61:in `run'
/home/gemowner/pkg/lib/rake/application.rb:129:in `standard_exception_handling'
/home/gemowner/pkg/lib/rake/application.rb:59:in `run'
/home/gemowner/pkg/bin/rake:32

reactor% rake -V
rake, version 0.9.2
</pre>

I would expect that `-t` should work regardless of where it is given.

(There is no rubygems on this system.)

**Comment by jimweirich** [comment]
-T takes an argument, so -Tt means search for all the tasks that have a "t" in the task name.

This behavior is defined by the optparse library.
