### ISSUE TITLE
Why Rake::FileList#egrep opens files in binary mode?

### ISSUE THREAD

**Issue by unak** [jimweirich/rake#74]
It makes 2 failures in test with dosish platforms (see bottom of this message).
I think there is no reason to open files in binary mode, especially reading them by IO#each(_line) method.

  1) Failure:
test_egrep_with_output(TestRakeFileList) [C:/Users/usa/ruby/test/rake/test_rake_file_list.rb:345]:
--- expected
+++ actual
@@ -1,2 +1,2 @@
-"xyzzy.txt:2:XYZZY
+"xyzzy.txt:2:XYZZY\r
 "

  2) Failure:
test_egrep_with_block(TestRakeFileList) [C:/Users/usa/ruby/test/rake/test_rake_file_list.rb:356]:
--- expected
+++ actual
@@ -1,2 +1,2 @@
-["xyzzy.txt", 2, "XYZZY
+["xyzzy.txt", 2, "XYZZY\r
 "]

**Comment by luislavena** [comment]
@drbrain and @jimweirich, can you guys look at this and Issue #72?

Thank you.

**Comment by rctay** [comment]
This would be fixed in https://github.com/jimweirich/rake/pull/92.

**Comment by jimweirich** [comment]
Fix in HEAD.  Will be in next release.
