### ISSUE TITLE
Rake error message when tests fail using TestTask

### ISSUE THREAD

**Issue by trans** [jimweirich/rake#78]
When using the TastTask and there are errors or failures in the tests, Rake ends output with:

```
rake aborted!
Command failed with status (1): [/usr/local/bin/ruby -I"lib:test" -I"/usr/l...]

Tasks: TOP => test
(See full trace by running task with --trace)
```

 I don't see why failed tests cause rake to abort as if Rake itself failed.

At the very least is there any way to surpress this output? I tried -s and -q.

If it matters I am using ruby 1.9.3dev (2011-07-03 trunk 32372) [x86_64-linux] and rake, version 0.9.2.1.

**Comment by drbrain** [comment]
Rake aborts so further tasks that depend upon a successful test run do not run (like packaging and releasing a gem).  There is no way to suppress this, it is by design.

**Comment by trans** [comment]
"Rake aborts so further tasks that depend upon a successful test run do not run (like packaging and releasing a gem)" 

Obviously. But the test task should not produce this _error message_ b/c a test failed. It's not the same thing as something actually raising an error in Rake's execution itself.

**Comment by drbrain** [comment]
Rake uses a child process to run the tests and relies on the exit code of the child process running the tests to determine the result.  Rake considers a non-zero exit to be a failure but rake doesn't know what the exit code means, it could be a test failure, a syntax error, or any other error raised by the child process.

Rake only has a single way of notifying the user of what went wrong.  I don't see the utility in detecting the difference between non-zero exit codes, exceptions raised by tasks and exceptions raised by bugs in rake.

**Comment by damphyr** [comment]
This has more to do with how the TestTask is implemented than anything else.

You have two options in order to improve the output: re-implement the TestTask so that it does not shell out but executes the tests within the rake ruby process and then handle the exceptions or invoke the TestTask within another task and rescue the exception:

```
begin
  Task['test'].invoke
rescue
  raise "tests failed"
end
```

**Comment by drbrain** [comment]
Tests may raise an exception that cannot be rescued (fatal, from a deadlock), may raise a confusing exception (SystemExit, Interrupt), or my crash (C extension bug) so running in a subshell is the only guaranteed way to behave correctly.
