### ISSUE TITLE
Allow for additional load_paths

### ISSUE THREAD

**Issue by grosser** [jimweirich/rake#80]
I currently keep my tasks in app/tasks and it would be nice if something like
`Rake.task_load_paths << 'app/tasks'` gets them loaded

so I do not have to do a `Dir.glob('app/tasks/*.rake').each { |r| import r }`

**Comment by drbrain** [comment]
Try adding this to your shell environment:

```
export RAKEOPTS='-R app/tasks'
```

**Comment by grosser** [comment]
Not bad, but I am looking for a more in-process approach... (so I can put it into my Rakefile)

**Comment by jimweirich** [comment]
You can now say this in your rakefile:

```
Rake.add_rakelib 'app/tasks', 'lib/tasks'
```

Change is on rake HEAD.
