### ISSUE TITLE
Variable declaration order issue

### ISSUE THREAD

**Issue by zimbatm** [jimweirich/rake#85]
Yet another follow-up of issue #82.

Since there is no rake mechanism to declare constants, ruby constants are often uses to describe things like a build path or defaults. Because those are not declarative, "rakelib/*.rake" file inclusion order then rapidly start to matter when you start to have cross-dependencies.

I propose to introduce a "var" task that defines the value of it's name after the declaration phase.

**Comment by kagminjeong** [comment]
The workaround/solution is to use blocks for definitions, at which point definitions are evaluated when they are used.

How would you propose improving on the current `set :foo, { definition }` syntax?

**Comment by zimbatm** [comment]
I'm not aware of rake supporting the `set` method but it's something like that that I had in mind.

**Comment by kagminjeong** [comment]
Sorry, that clearly was capistrano and not rake syntax. My mistake.

**Comment by sunaku** [comment]
Why not use an OpenStruct object to house all of your "constants" and read/write/override them as you wish?

``` ruby
# some_lib.rb
require 'ostruct'
MY_QUOTE_CONSTANTS = OpenStruct.new
task :foobar do
  puts "now do something with #{MY_QUOTE_CONSTANTS.something}"
end

# Rakefile
require './some_lib'
MY_QUOTE_CONSTANTS.something = "that foobar thing!"
task :catdog do
  MY_QUOTE_CONSTANTS.something = "that catdog thing!"
  Rake::Task[:foobar].invoke
end
```

And now to run the above code:

``` sh
$ rake foobar
(in /tmp)
now do something with that foobar thing!
$ rake catdog
(in /tmp)
now do something with that catdog thing!
```

KISS, and more importantly, keep Ruby/Rake simple please!
