### ISSUE TITLE
FileList[] passed a string without a "*" will always return the string provided even if it does not match a file

### ISSUE THREAD

**Issue by dkubb** [jimweirich/rake#9]
When using FileList[], if you pass a string without "*", and the string references a file that does not exist, it will always return an Array containing the string. I always thought the behaviour was similar to Pathname.glob, which only returns matching files.

How to reproduce:

```
require 'rake'
puts FileList['nonexistent_file.txt']  # => ["nonexistent_file.txt"]
```

**Comment by dkubb** [comment]
Sorry, I didn't see the FileList#existing method before now. Based on examples of FileList usage I've seen, I always assumed it returned the matching files.

**Comment by jimweirich** [comment]
If it only included existing files, I couldn't create a list of files that I wanted to create.
