### ISSUE TITLE
shouldn't create directory on root directory (Windows issue)

### ISSUE THREAD

**Issue by unak** [jimweirich/rake#91]
In test/rake/test_rake_directory_task.rb, there is a hardcoded directory 'c:/a/b/c', and the test  code creates 'c:/a/b' actually.
Furthermore, the directory is left behind, without being deleted.
This is very intolerable.

**Comment by unak** [comment]
see r33885 of MRI trunk.

**Comment by rctay** [comment]
Backported fix in #93.

**Comment by jimweirich** [comment]
Fixed in next version
